### PR TITLE
ClicknUpload plug-in

### PR DESCRIPTION
**Pull request by tbsnpy**
* Rewrite of ClicknUpload plug-in
* Makes plug-in from #2455 obsolete

### CODE REVIEW

**Comment by vuolter** [comment]
@tbsnpy Usually do you write code in C? :)

**Comment by tbsnpy** [comment]
@vuolter Hehe^^ Yes. I've been using C for some time, now. Old habits die hard.

**Comment by tbsnpy** [comment]
Please note the below link for testing purposes.

http://clicknupload.link/n69fbflcbnym

**Comment by kb0n** [comment]
Do I need to activate/change anything for this to work?
All I get is this (on a fresh pyload-setup on RaspPi2):
```
12.05.2016 16:07:01 INFO      Added package test containing 1 links
12.05.2016 16:07:01 INFO      Download starts: http://clicknupload.link/n69fbflcbnym
12.05.2016 16:07:01 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
12.05.2016 16:07:01 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
12.05.2016 16:07:01 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | Plugin version: 0.64
12.05.2016 16:07:01 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | Plugin status: testing
12.05.2016 16:07:01 WARNING   HOSTER XFileSharing[2]: ClicknuploadLink | Plugin may be unstable
12.05.2016 16:07:01 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | Config option `use_premium` not found, use default `True`
12.05.2016 16:07:01 INFO      HOSTER XFileSharing[2]: ClicknuploadLink | Grabbing link info...
12.05.2016 16:07:02 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | Link info: {'status': 2, 'hash': {}, 'name': u'test.txt', 'url': u'http://clicknupload.link/n69fbflcbnym', 'pattern': {'N': u'test.txt'}, 'size': 0}
12.05.2016 16:07:02 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | Previous link info: {}
12.05.2016 16:07:02 INFO      HOSTER XFileSharing[2]: ClicknuploadLink | Link name: test.txt
12.05.2016 16:07:02 INFO      HOSTER XFileSharing[2]: ClicknuploadLink | Link size: N/D
12.05.2016 16:07:02 INFO      HOSTER XFileSharing[2]: ClicknuploadLink | Link status: online
12.05.2016 16:07:02 INFO      HOSTER XFileSharing[2]: ClicknuploadLink | Processing url: http://clicknupload.link/n69fbflcbnym
12.05.2016 16:07:02 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | LOAD URL http://clicknupload.link/n69fbflcbnym | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
12.05.2016 16:07:02 INFO      HOSTER XFileSharing[2]: ClicknuploadLink | Checking for link errors...
12.05.2016 16:07:02 WARNING   HOSTER XFileSharing[2]: ClicknuploadLink | Size: 10 B
12.05.2016 16:07:02 DEBUG     HOSTER XFileSharing[2]: ClicknuploadLink | Config option `fallback` not found, use default `True`
12.05.2016 16:07:02 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
12.05.2016 16:07:02 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
12.05.2016 16:07:02 WARNING   Download failed: test.txt | File too large for free download
12.05.2016 16:07:02 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: test.txt (pid:2)
12.05.2016 16:07:02 INFO      ADDON UnSkipOnFail: No duplicates found
12.05.2016 16:07:02 DEBUG     ADDON ExternalScripts: No script found under folder `download_failed`
12.05.2016 16:07:02 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
12.05.2016 16:07:02 DEBUG     All downloads processed
```
This looks suspicious to me: `Plugin version: 0.64`

**Comment by GammaC0de** [comment]
You should disable XFileSharing plugin

**Comment by kb0n** [comment]
> You should disable XFileSharing plugin

Ok, thanks. I thought XFileSharing was a crucial plugin, handling multiple other hosters and all those that don't have a dedicated plugin (so now that CNU had one, it would be prefered to XFileSharing). So I was worried about deactivating it. Guess I'll just have to monitor the overall behaviour for a while.

**Pull request closed without merging**
