### PR TITLE
Add LinkFilter plugin

### PR DESCRIPTION
**Pull request by segelkma**
- LinkFilter

This simple plugin allows to filter all added links.

Example: The filter "random-url.com" will remove all links from queue containing it such as http://random-url.com/fileabc.rar
Multiple filters can be set by seprerating them by comma: "filter1.com,filter2.com"

Example usage: Sort out hosters when a dlc contains multiple hosters.

Future versions: Reverse filter (only allow given filter + option not to filter containers (dlc's))

References: #2519 #182

### CODE REVIEW

**Comment by GammaC0de** [comment]
:+1:

**Comment by segelkma** [comment]
Thanks for cleaning up!
Unfortunately the plugin won't activate now:
> 19.11.2016 17:39:13	DEBUG	created index of plugins
> 19.11.2016 17:39:13	DEBUG	Redirected import module.plugins.hooks.LinkFilter -> userplugins.hooks.LinkFilter
> 19.11.2016 17:39:14	WARNING	Failed activating LinkFilter

**Comment by GammaC0de** [comment]
Checking.. 

 

   
Thanks for cleaning up!
Unfortunately the plugin won't activate now:


19.11.2016 17:39:13 DEBUG created index of plugins
19.11.2016 17:39:13 DEBUG Redirected import module.plugins.hooks.LinkFilter -> userplugins.hooks.LinkFilter
19.11.2016 17:39:14 WARNING Failed activating LinkFilter

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/848daef25097ff2f5ae0db6564e2aab709bcbd95 Fixed.

**Comment by segelkma** [comment]
Yup, works again. But is it wanted that you have to restart pyload to turn off the plugin? I mean you could otherwise just empty the filterlist (would not turn it off, but would do nothing then) but maybe not everyone is aware of that.

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/commit/291f4470596f3989f4cf3c3b78e32c0a185091cd

**Comment by xcy7e** [comment]
How can I download the plugin and get it work inside jdownloader2?

**Comment by GammaC0de** [comment]
@xcy7e What!?
This is a plugin for pyLoad, not jdownloader.

**Pull request merged**
