### PR TITLE
Add support for jinja2 2.7.X

### PR DESCRIPTION
**Pull request by theluckyluke**

### CODE REVIEW

**Comment by vuolter** [comment]
Please, apply on master branch, stable is for plugin updates only. ;)

**Comment by theluckyluke** [comment]
That's kind of weird :)

**Comment by vuolter** [comment]
Last time I changed something else on stable branch, there was an insurrection... O.O

**Comment by theluckyluke** [comment]
Looks like this problem does not arise on the master branch.

**Pull request closed without merging**
