### PR TITLE
[Main] Fix start webserver if address is already in use

### PR DESCRIPTION
**Pull request by OzzieIsaacs**
### Describe the changes

Change code for webserver start similar to cnl-server restart. So with a port already in use, pyload-ng tries to start the webserver 4min later again.

Remark: From my point of view, the restart routine for the cnl load proxy and the werbsever aren't ideal, as this consumes more and more memory with each restart. As you are going deeper and deeper into recursion calls of "run" routine. A while loop with break might be better

### Is this related to a problem?

If you start pyload-ng with an already in use port the program creates the following error (address already in use):

```
[2020-11-06 18:12:13]  DEBUG               pyload  *** pyLoad is up and running ***
[2020-11-06 18:12:13]  ERROR         pyload.webui  Keyboard Interrupt: shutting down
Traceback (most recent call last):
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1710, in safe_start
    self.start()
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1818, in start
    self.prepare()
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1778, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('127.0.0.1', 8000): [Errno 98] Die Adresse wird bereits verwendet)
python-BaseException
Traceback (most recent call last):
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1710, in safe_start
    self.start()
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1818, in start
    self.prepare()
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1778, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('127.0.0.1', 8000): [Errno 98] Die Adresse wird bereits verwendet)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/webserver_thread.py", line 77, in run
    self._run_produc()
  File "/home/ozzie/.local/lib/python3.8/site-packages/pyload/webui/webserver_thread.py", line 58, in _run_produc
    self.server.safe_start()
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 1715, in safe_start
    self.stop()
  File "/home/ozzie/.local/lib/python3.8/site-packages/cheroot/server.py", line 2114, in stop
    self._connections.close()
AttributeError: 'Server' object has no attribute '_connections'
```

### Additional references

Tested with Linux Mint 20 and python3.8

### CODE REVIEW

**Comment by GammaC0de** [comment]
What is the reason you get address is already in use error?

I'd rather quit pyLoad if address is already in use (as I did in https://github.com/pyload/pyload/commit/313c7a51250b990856f80c4be971409b768cf74f for `stable`).
If not, you would get some unexpected results.

**Comment by OzzieIsaacs** [comment]
It has nothing to do with pyload, it‘s just the usecase another program is currently using the port pyload wants to use.
I think we should not generate a traceback, another option solving this would be to quit pyload in this case

**Comment by OzzieIsaacs** [comment]
Shall I change the PR to quit pyload in this case?

**Comment by GammaC0de** [comment]
No need, I already have the changes.

**Comment by GammaC0de** [comment]
Thanks

**Comment by GammaC0de** [comment]
> Remark: From my point of view, the restart routine for the cnl load proxy and the werbsever aren't ideal, as this consumes more and more memory with each restart

The _`server()` function uses the `threaded` decorator which causes the function to start in a new thread and return imminently, hence no recursion is done.

**Comment by OzzieIsaacs** [comment]
Thanks @GammaC0de for clarifying, but anyhow you fix makes this obsolete

**Pull request closed without merging**
