### PR TITLE
smule hoster plugin, using updated JsEngine code (see Issue #2402)

### PR DESCRIPTION
**Pull request by igel-kun**
This "hoster" needs some javascript evaluated, so I took the liberty of updating ```/modules/common/JsEngine.py``` as it wasn't supporting the js engine I run (node_js)

### CODE REVIEW

**Comment by GammaC0de** [comment]
Hi, In 'stable' branch, you cannot change anything besides "plugins" directory.

Also for changes in 'internal' directory you should create a separate PR because it effects *all* the plugins so @vuolter has to approve it.

**Comment by igel-kun** [comment]
So, what do I do with the change to ```JsEngine.py``` which the hoster implementation depends on?

**Comment by GammaC0de** [comment]
@igel-kun Isn't the current implementation of `JsEngine.py` enough?

**Comment by igel-kun** [comment]
the current implementation forces ```eval(unescape('<script>'))``` on the script, which is OK for simple scripts but not OK for more complicated stuff containing variable and function declarations (so I added ```eval_raw()```). Secondly, it doesn't support ```Node JS``` which I happen to run, as it does not have a ```print``` command, but it uses ```console.log``` (so I added detection for ```Node JS```).
If I had left the current infrastructure unchanged, these two changes would have incurred silly code, so I had to change some supporting code.

Here's the problem with the old engine:
```
$ python2 -m module.common.JsEngine
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "module/common/JsEngine.py", line 162, in <module>
    js.eval(test)
  File "module/common/JsEngine.py", line 101, in eval
    raise Exception("No JS Engine")
Exception: No JS Engine
$ js -e 'console.log(23+19)'
42
$ file /usr/bin/js /etc/alternatives/js
/usr/bin/js:          symbolic link to /etc/alternatives/js
/etc/alternatives/js: symbolic link to /usr/bin/nodejs
```

Okay, now that I think of it, maybe the ```eval_raw()``` can be emulated with a bit more javascript-fu, which I don't have...

**Comment by GammaC0de** [comment]
- What platform are you running?
- Do you have sample link to test this?

**Comment by degs01** [comment]
rpi2 rasbian jessy 
no link

**Comment by igel-kun** [comment]
same configuration here, a sample link can be found in the original issue #2402 I think

**Comment by igel-kun** [comment]
ah nice, thanks for the adaptation! This additional ```get_info``` to add ".mp4" will also be necessary for #2561 I'm afrait... I'll update that PR later on...

**Comment by GammaC0de** [comment]
:+1: 

Sorry for the dumb question, but what exactly is ARD?

**Comment by igel-kun** [comment]
It's not at all a dumb question! ARD is one of Germany's public broadcasters. As their broadcasting is public, they keep the most recent shows around in what they call "medithek" for anyone (an IP registered to a German ISP might be required tho, not sure) to watch in case they missed it. See https://en.wikipedia.org/wiki/ARD_(broadcaster)

**Pull request closed without merging**
