### PR TITLE
[Extractor] Targets didn't use quotation marks

### PR DESCRIPTION
**Pull request by immenz**
Think that causing https://github.com/pyload/pyload/issues/1219

### CODE REVIEW

**Comment by mbosner** [comment]
@vuolter could you please merge this? Would you consider granting immenz pull rights?

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/8b432eb80715f84800febb88620d943211e28051
If @immenz wants to join the pyLoad Team, he has to ask for it and I'll talk about with the other members. :)

**Comment by immenz** [comment]
Thanks, but at the moment it is good as it is.

**Comment by vuolter** [comment]
No problem. ;)

**Comment by immenz** [comment]
Why did you have reverted your changes and not just edit the quotation marks? 
Thought it was some kind of preparation for 1.4.10 ?

**Pull request closed without merging**
