### PR TITLE
[RapidgatorNet] Fix accountless downloads

### PR DESCRIPTION
**Pull request by HimbeersaftLP**
### Describe the changes

I fixed free Rapidgator downloads by updating the regular expression to include the https protocol.

### Is this related to a problem?

Previously, it would keep looping between "Waiting" and asking for a Captcha, now it works again.

### Additional references

None

### CODE REVIEW

**Comment by GammaC0de** [comment]
Increase version please

**Comment by GammaC0de** [comment]
Opps, the PR should be against the `stable` branch

**Comment by HimbeersaftLP** [comment]
Sorry, I'll create another one

**Comment by HimbeersaftLP** [comment]
Done: #3784

Why does GitHub have to make retargeting a PR that hard...

**Pull request closed without merging**
