### PR TITLE
[Main] Fix link move_package erroneous

### PR DESCRIPTION
**Pull request by OzzieIsaacs**
### Describe the changes
in json_blueprint the move_package route is wrong it uses a pipe instead of a slash, this leads to a traceback upon pressing move_package:

```
[2020-10-24 08:24:58]  DEBUG         pyload.webui  404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
Another problem with the links was that the variable target could not be inserted in the package.js file (code in line 3-7). This lead to a NaN in the "/json/move_package" route generated. I reverted the code to the original one, the javascript for creating packageUI class is now called in the html fil again

**Comment by GammaC0de** [comment]
Personally I use the pyplex theme so I did not spotted these bugs.
Please test my changes and report, thanks.

**Comment by OzzieIsaacs** [comment]
I copied your last changes over to my instance, restarted pyload-ng, the error is still persisting:
grafik
grafik

I'm using firefox 82.0 on Linux Mint 20.1

**Comment by OzzieIsaacs** [comment]
I doublechecked it with Chromium on the same computer, with the same result (used inkocknito tab to encure it#s not an caching issue):
grafik
```

werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2020-10-25 08:18:12]  DEBUG         pyload.webui  404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```
With the original code you could see while debugging the js code that the {{target}} variable wasn't present, it just was resolved to nothing.

**Comment by GammaC0de** [comment]
This is weird,
for me it works both with the Default and pyplex themes.

{{target}} is not used anymore in the javascript file so this surely not the cause of this issue.

Please clone a fresh debug branch and test there, thanks.

**Comment by OzzieIsaacs** [comment]
I doublechecked it, your code is definitly not working for me.
I agree with you that the pipe to slash change was a unnecessary change, I reverted it.
Just to clarify: We are talking about the pyplex theme and trying to move a package from Queue to Packages page and back. This is done by the two lying arrows beside each package (and we are not talking about changing the order of packages on a page)

I try to explain my point of view:
"target" was used to indicate if packes.js is loaded from the queue or packages page. You now removed this variable and also the setting of this variable in the PackageUI class. 
With my patch PackageUI is created with parameter target 0 or 1 depending on which page it was called. Then it's assigning type to self.type during intitialization. In parsePackages function for each package a new instance of class Package is created, the first parameter is a link to PackageUI class (thisObject). In the Package class constructor the first parameter is called ui, which is  thisObject (PackageUI oject in constructor). In line 313 of package.js the reference to ui.type is used to generate the link for moving the package. 
With your patch ".type" is nowhere assigned in the whole code, who is this variable read out with your patch?? 

I can only guess that on your system the not initialized variable is set to zero instead to NaN like on my system and therefore it looks like it's working. Can you really move a package from Queue to Packages and back?

**Comment by GammaC0de** [comment]
OK, great explanation 👍 
Now I see what you meant.
I thought you were referring to package order movement which was not working either.

I can now reproduce this issue on my system.

**Comment by OzzieIsaacs** [comment]
Great

**Pull request closed without merging**
