### PR TITLE
Recaptcha v2 overhaul

### PR DESCRIPTION
**Pull request by Arno-Nymous**
Now this should finally work. I just added some code lines to distinguish between Windows and Linux and made some minor improvements. Check it out, I would be delighted if this made it into the project :wink:

Sorry for introducing the requests module, but I don't know any way to send headers with the `load` method that PyLoad offers me. I needed to send a referer together with my requests, so I chose this path. If you know, how to do it with the existing code, please tell me.
The BeautifulSoup module is just out of comfort. One could probably do it with a few lines more utilizing regular expressions and stuff, but since other plugins use BS as well I thought it'd ok :sweat_smile:

**P.S.:**
Thought it would be worth mentioning it here as well that ReCAPTCHA v2 captchas will now look similar to this:

captcha

### CODE REVIEW

**Comment by vuolter** [comment]
O.O

**Comment by Arno-Nymous** [comment]
@vuolter
>O.O

What's this? :joy:

**Comment by vuolter** [comment]
I am speechless, see my eyes! ;)

**Comment by wastez** [comment]
It´s working totaly great, thanks for your hard work.

**Comment by GammaC0de** [comment]
@Arno-Nymous I took this PR as a base for https://github.com/pyload/pyload/commit/93c0627b1d05212cc4f08d4518309f977dfdff90.

Great job, thanks! :+1: :+1:

**Pull request closed without merging**
