### PR TITLE
Some small issue fixes

### PR DESCRIPTION
**Pull request by Arno-Nymous**
Here is the announced pull request from #2207. Maybe you have to do some cherry picking. The changes are rather small hence the commits have no dependencies between each other.

### CODE REVIEW

**Comment by vuolter** [comment]
Only plugin updates can be merged in stable branch + no warez stuff allowed!

**Comment by Arno-Nymous** [comment]
Isn't it possible to just pull the commits relevant to the project and leaving out the rest? Since each commit only applies to a single file this shouldn't be that big of a deal.

**Comment by vuolter** [comment]
Sure, you can open a new PR or wait until I edit this, but I'm currently working on other stuff, so it may take a few days. :S

**Comment by vuolter** [comment]
Done. :)

**Pull request merged**
