### PR TITLE
Redesigned webinterface with bootstrap css

### PR DESCRIPTION
**Pull request by mariusbaumann**
I now found time to redesign the webinterface of pyload. Probably you like it. 

General changes:
- New style on every page
- New head-menu
- Completely new icon-set
- New status lables with color for eatch status
- New styled progress bars
- Completely redesigned and reformated settings page
- Redesigned overlay-windows
- Some html formate changes 
- More responsive design (not on queue page, there i sitll have some problems with the javastcript generated ui)

Important: I have nothing changed on the functionality of pyload, only the frontend of the webinterface has changed. On some pages i had to make little changes on the javascript to generate the html in the right structure (on exsample for the new icon i had to change the tags from img to span so i had to change the javascript to reacting on the span tags) 

I hope you like it :) 

Now some screenshots:

bildschirmfoto 2015-01-03 um 07 07 55

bildschirmfoto 2015-01-03 um 07 08 11

bildschirmfoto 2015-01-03 um 07 08 52

bildschirmfoto 2015-01-03 um 07 09 10

bildschirmfoto 2015-01-03 um 07 08 29

### CODE REVIEW

**Comment by vuolter** [comment]
Nice! :D 
I have to adapt it to the master branch before merging, but I think will not be hard. ;)
Thanks!

**Comment by RaNaN** [comment]
The webUI in the 1.0.0 branch is already based on bootstrap. If possible, additional work should be done on this version.

**Comment by vuolter** [comment]
I really need time to check all these interesting stuff... :P

**Comment by Gutz-Pilz** [comment]
NICE!!!!
is there a way to embed it manually in my pyload installation?
just change the files ?
PN ?

**Comment by mariusbaumann** [comment]
yes it should work if you change the same files.

**Comment by vuolter** [comment]
I don't see any captcha popup when captcha request was fired. :S

**Comment by mariusbaumann** [comment]
ok, i did, tested with shareonline.biz. I'll try to fix that

**Comment by stickell** [comment]
Wonderful! These are the kind of pull requests I like! Great job Marius :+1: 

In my opinion instead of overwrite the `default` template it's better to put this in a new separate folder with a new name. Obviously we will make this the new default template in 0.4.10 but keeping the old one will allow some mad user to revert to that if they prefer.

**Comment by stickell** [comment]
Bootstrap 3.3.2 has been released.
Also isn't better to import the minified version instead of the full one for performance reason? I know let's say 90% of users runs pyLoad localhost but for those who controls it over the internet could be a little time/bandwidth saver trick.

**Comment by mariusbaumann** [comment]
so i've tested the captcha issue, and i'm sorry, but i cant't find a problem. In Safari, Firefox, Chrome it is working. Is it possible to describe the issue little bit mor precise? Which brwowser, hoster, plugins did you use for testing?
bildschirmfoto 2015-01-30 um 21 05 13

**Comment by mariusbaumann** [comment]
@stickell  you realy right, the users they like to use the old GUI further, they really mad :) but i will see for a separation of the template, if its not to complexe. 
The new bootstrap i can add in a free minute. The minified version ist still in use because the template imports only this but i'll doubble check this, and clean the folder if ther are unused files.

**Comment by stickell** [comment]
> but i will see for a separation of the template, if its not to complexe. 

Don't worry about that, we will take care on merge!

> The minified version ist still in use

In `base.html` I see:
```html
<link rel="stylesheet" href="/media/default/css/bootstrap/bootstrap.css">
```
which is the full version, in my opinion you should change to:
```html
<link rel="stylesheet" href="/media/default/css/bootstrap/bootstrap.min.css">
```

**Comment by mariusbaumann** [comment]
@stickell template: oh that's nice, thanks. The CSS issue is fixed.

**Comment by stickell** [comment]
You have committed a strange `tmp` folder.

**Comment by wastez** [comment]
IT´s looks really great. Great Job.

Just the "new captcha" notification crosses the other windows on low resolution.

**Comment by immenz** [comment]
Is it possible to make the config area floating? 
Especially the Plugin-Config, where are about 1000 plugins felt...

**Comment by stickell** [comment]
> Is it possible to make the config area floating?
Especially the Plugin-Config, where are about 1000 plugins felt... 

You are right. This is an irritant issue in 0.4.9

**Comment by wastez** [comment]
I saw right now that the download status in the queue  is also not refreshed automaticly.

**Comment by wastez** [comment]
In the log section a refresh button would be also good.

Are you still working on it?

**Comment by I-RiX-I** [comment]
I absolutely love the design changes. One really annoying thing though is the missing package management.

After implementing your changes as of today, I am no longer able to remove packages from the queue or even rearrange them... if this is intentional it needs a fix.

**Comment by wastez** [comment]
There is no fix needed. Just delete your browsercache.

**Comment by Gutz-Pilz** [comment]
i'm scared to move and replace all those files...
is there a little workaround for that or a tutorial?

**Comment by I-RiX-I** [comment]
Thanks wastez. You were right
Gutz-Pilz, I will send you a file

**Comment by I-RiX-I** [comment]
Gutz-Pilz. Just extract what I pm'ed you in the forum into your pyLoad\dist folder and set the theme to default under Settings\Webinterface

**Comment by mariusbaumann** [comment]
> Is it possible to make the config area floating? 
> Especially the Plugin-Config, where are about 1000 plugins felt...

I have tried it, but i found no way to make the left list scrollable only. If i position-fix the settings-srea in some resolutions not the full content shows up, some fields or buttons aro of the screen. But i'll do a deeper research, probably someone of you have a grate idea to arange the plugins in a beautiful way?

**Comment by mariusbaumann** [comment]
> Just the "new captcha" notification crosses the other buttons on low resolution. 

I'll fix that. 

> It would be also great if the mouse course will select the field automaticly if the captcha enter field appears, so that we can enter the captcha without moving the mouse first.

Good idea, thanks, i'll try to fix that. 

> I saw right now that the download status in the queue is also not refreshed automaticly.

This was no feature before. My goal is to redesign the interface, if you thinkt there should be a refreshing function, you probably ask someone konws more about the javascript part of the project. 

> In the log section a refresh button would be also good.

Also here. If there is no button before redesign, than there is no button after, because redesign is neither adding buttons nor adding some other functionaliy.

This should not sound angry, it was only not in my focus.

**Comment by I-RiX-I** [comment]
Great redesign. One annoying thing though: I cannot move packages up/down the list. Is this intentional? (Tested on multiple devices)

Also, when running pyload behind a reverse proxy the glyphicons from bootstrap.css stop working.

**Comment by wastez** [comment]
@I-RiX-I 
The packages can´t be moved in the default webinterface too.

I´m running pyload also behind a reverse proxy for https and have no problems with any icons.

**Comment by ohaucke** [comment]
@wastez you can move packages with drag&drop in the default webinterface
move

**Comment by wastez** [comment]
that´s is a interessting thing, didn´t know that, my fault.

And yes, this is a very good function.

**Comment by wastez** [comment]
Ok, found the function.
It´s implemented if the "move package" button is pressed and moved.

**Comment by mariusbaumann** [comment]
oh sorry, in this case i missunderstood the function of this move button. I'll fix that.

**Comment by mariusbaumann** [comment]
@wastez your drag and drop issue is fixed.

**Comment by wastez** [comment]
Now it´s ok, movement is working on the text of the download.

**Comment by I-RiX-I** [comment]
Thank you for fixing this.

**Comment by mariusbaumann** [comment]
Thanks to m4xcube the plugins list is now scrollable!

**Comment by mariusbaumann** [comment]
thanks to @m4xcube  the pakage size is now displayd at anytime. I have changed the color and textstyle for better readability

**Comment by vuolter** [comment]
:+1:

**Comment by mariusbaumann** [comment]
@vuolter i'm a little bit confused about your last comment. In the commit 623f882 are two conflicts, should i fix some thing?

**Comment by vuolter** [comment]
Everything is ok: I started merging your commits so far, fixing conflicts time to time. ;)

**Comment by mariusbaumann** [comment]
Ok thanks.

**Comment by vuolter** [comment]
@mariusbaumann http://forum.pyload.org/viewtopic.php?f=7&t=3071&p=18201#p18138 Bug spotted?

**Comment by mariusbaumann** [comment]
ok, i'll check this.

**Comment by c0rrre** [comment]
I got the same behavior on long package names

**Comment by wastez** [comment]
Hello marius.
Can you have a look on your latest release of this skin.
On lower resoltutions the buttons are to small in some cases.
Can you fix it? Here is a screenshot:

bildschirmfoto 2016-02-29 um 21 30 53

**Comment by obi12341** [comment]
Hello guys,

if you just want to take a quick look on the new design (like me) and you are able to run docker, I've build a new tag:

```docker run -d -P writl/pyload:new-design```

https://hub.docker.com/r/writl/pyload/

**Comment by vuolter** [comment]
@obi12341 :+1:

**Comment by wastez** [comment]
@vuolter 
You marked this as unmergeable, so it will not be the next skin for pyload?

**Comment by vuolter** [comment]
Was marked as `unmergeable`, because this PR is `unmergeable` with 0.4.10, but I already made it compatible with it, so don't worry. :p
This PR is currently `mergeable` with 0.4.9 .

**Comment by dischinator** [comment]
@wastez @mariusbaumann I can take a look at this, I think it's me who borked this ;)
I also have some more stuff for you to merge I think.

**Comment by wastez** [comment]
@dischinator 
If you are on the way there is something else. 
Captchas from Share-links are not displayed in this Skin.

**Comment by vuolter** [comment]
@dischinator :+1:

**Comment by dischinator** [comment]
I opened a pull request to @mariusbaumann that makes the menu buttons more dynamic to fix problems with long text.

**Comment by wastez** [comment]
What about the problem with the captchas?

**Comment by wastez** [comment]
@dischinator 
I have to say that this captchas are working in the Original Skin.

**Comment by GammaC0de** [comment]
What about co-existence with other themes (i.e. the old `default` theme) ?

I want to be able to choose between this theme and the `default` theme, currently the default theme doesn't work well with this patch applied..

The `media/js` folder seems to be common for all themes..

**Comment by wastez** [comment]
@dischinator 
Now everything is ok. 
Your mobile version is looking Great. 
The only thing is the captcha request Dialog which is over the Buttons. 
And the log could be customized, both is in the following Screenshot. 
Thanks for your great work. 
image

**Comment by GammaC0de** [comment]
One bug I spotted:
On the active downloads screen, after "status" and "name" there is missing "Information" table header so "size" and "progress" are one position to the left
capture

**Comment by b3rnhard** [comment]
I have been experimenting with this a bit. Right now, login does not work anymore, I am not sure, whether it is my fault by copying the changed files over a working pyload installation or not. When not logged in, in base.html ```{% if perms.STATUS %}``` is false, then some button-ids (e. g. "action_play") are missing and the base.js is not executing until the end. I am not getting any errors, just the login page. No cookie is set. When I comment out the if-endif part from line 112 to 119, login works again.

**Comment by jbatmall** [comment]
Hi,
I test it and it's great job! I see a little issue in french language

sans titre 2

**Comment by gsantner** [comment]
Are there any updates on this?

**Comment by clouless** [comment]
@mariusbaumann hi, awesome work :) Do you need any help on this? I would love to see that merged to master :)

**Comment by Burnout5151** [comment]
Yeah, I like the look and it would symbolise the new start that is being worked on in Version 0.5/1.0

**Comment by gsantner** [comment]
@mariusbaumann The old/current version of pyload didn't pay much attention to make it work e.g. via revrerseproxy. Could you please reference directories that way so this works also if it's not in the root directory (but e.g. domain.com/pyload/)
Thanks!

**Pull request closed without merging**
