### PR TITLE
suggestion [XFSCrypter] use HTMLParser instead of regular expressions

### PR DESCRIPTION
**Pull request by GammaC0de**
Hi,
I would like to suggest using HTMLParser  for grabbing links inside html <TD> tags
This way it is more robust  and chances for false positive are near zero.
even after last commit, XFSCrypter does not catch cases like:
```
<td class="title-link">
<a href="http://uplea.com/dl/A3B488FFCF93F3F">http://uplea.com/dl/A3B488FFCF93F3F</a>
<img style="margin-top:-3px;" src="/img/file.png"/>
</td>
```
Performance is not degraded. 
So using  HTMLParser is better in my opinion.

What do you say?

### CODE REVIEW

**Comment by vuolter** [comment]
I want to explain why this PR was rejected (for now):
XFSCrypter is a wide used class, like SimpleHoster. For this kind of plugins we can not simply remove a key attribute like LINK_PATTERN, because many other plugins use it, and would go down otherwise. In future, if LINK_PATTERN becomes too complex, we may combine current regex behaviour with HTMLParser. ;)

**Comment by GammaC0de** [comment]
Ok, thats fine, this is why I wrote `suggestion` in the title :wink: 
one connent though:
the new LINK_PATTERN you added a new group but I think should use an unnamed group, ie:
`<a href="(.+?)".*?>.+?(?:</a>)?\s*(?:<.+>\s*)?</(?:td|TD)>`
```patch
-<a href="(.+?)".*?>.+?(?:</a>)?\s*(<.+>\s*)?</(?:td|TD)>
+<a href="(.+?)".*?>.+?(?:</a>)?\s*(?:<.+>\s*)?</(?:td|TD)>
```
or even better use  `<(?:td|TD).*?>\s*(?:<.+>\s*)?<a href="(.+?)".*?>.+?(?:</a>)?\s*(?:<.+>\s*)?</(?:td|TD)` which is better in my opinion.

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/7b095378cba22aa2cfadfd62699d77bf1724da41

**Comment by GammaC0de** [comment]
:thumbsup:

**Pull request closed without merging**
