### PR TITLE
[Click N' Load] Fix #2451

### LINKED ISSUE #2451: Names from site like filecrypt
Hello, since today or yesterday i see a small bug.
If i have load some files from filecrypt to pyload via click n load i get the folder name from filecrypt in pyload. looks like "xxx.1080p.x264-hermes -filecrpyt.cc". Now, i get only "filecrypt.cc". Where is the rest of the folder name?
I have also tested old files and have the same error.

### PR DESCRIPTION
**Pull request by GammaC0de**
Fix #2451

### CODE REVIEW

**Comment by Velociraptor85** [comment]
will this be auto updated? since there is no version tag in this ? @GammaC0de

**Comment by GammaC0de** [comment]
@Velociraptor85 It's not a plugin so UpdateManager cannot update it
It's a part of the core so it cannot get to the 'stable' branch (no changes to the core in 'stable' rule)
it has to be part of the next release.

**Comment by Mister-XY** [comment]
Ok, when come the next release?

**Comment by Velociraptor85** [comment]
@Mister-XY please check https://github.com/pyload/pyload/issues/2584

**Pull request merged**
