### PR TITLE
Update OneFichierCom.py

### PR DESCRIPTION
**Pull request by GammaC0de**
id is not needded anymore

### CODE REVIEW

**Comment by thadrien** [comment]
Thanks GammaC0de. This point was not clear for me.

**Comment by thadrien** [comment]
Hi,

Could someone explain to me why ID1 and ID2 where not in self.info['pattern'] although they were still in self.__pattern__ regular expression ?

Thanks,

**Comment by GammaC0de** [comment]
Ok,
Thanks to your question, I found the root cause of this bug and I think of #1979 too :)
see #1997 for fix

many thanks :smile:

**Comment by thadrien** [comment]
Thanks for your answer.
But, still don't understand something : why self.info['pattern'] was not
empty, and why they weren't any message about re module missing ?

**Comment by GammaC0de** [comment]
first of all, there was no self.info['pattern'] at all (at least when I checked).
as for message about re module missing, the exception was catched and ignored,
see [Base.py#L118](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/Base.py#L118)
```python
        try:
            info['pattern'] = re.match(cls.__pattern__, url).groupdict()
        except Exception:
            pass
```

**Comment by thadrien** [comment]
Thanks for your answer.
It was here when I checked this. I even insert a print instruction which
has shown its contents.
Catching exceptions without logging is not very safe. I will add something
to avoid this.

**Comment by GammaC0de** [comment]
Yes, I also thought so but the problem is that this is `@classmethod` function so there is no `self` variable and you can't use `self.log_error()`.
you cant use `print()`, but that wont be logged to the log file.
@vuolter is there any other method for logging that fits  to this case?

**Comment by thadrien** [comment]
But what about exception filtering ?

**Comment by vuolter** [comment]
@GammaC0de Maybe:
```
import logging
logger = logging.getLogger("log")
level = "error"
log = getattr(logger , level)
log("What you want is logged")
```

**Comment by thadrien** [comment]
@vuolter : thx for your answer. Are you already using python logging module
in the other parts of the code ?

**Comment by GammaC0de** [comment]
@vuolter how about adding a `pylog` function to `__builtin__` in v0.4.10 for these cases (this had already been done for `pyreq`)?

**Comment by vuolter** [comment]
In 0.4.10 should be pycore, so you should able to call pycore.log directly.

**Comment by GammaC0de** [comment]
:+1:  thats wonderful news :smile:

**Comment by thadrien** [comment]
Thx so much vuolter. Hope it will come soon, at least a preview.

**Comment by thadrien** [comment]
@vuolter : I think we should use one and only one logging system, because using two systems will make some sync problems between the two systems. Adding pycore to builtins seems a better solution to me, although I don't like global variables.

To avoid this problem to occur again, maybe we should filter exception, like this :
```python
except NameError:
  raise
except Exception:
  pass
```

**Comment by GammaC0de** [comment]
@thadrien the problematic part of you suggestion is:
```
except Exception:
  pass
```
so unhandled exception will still be ignored (that was the case in the first place) and you have to carefully think what type of exceptions can occur.

**Comment by thadrien** [comment]
@GammaC0de I totally agree with you. But at least it will avoid forgetting `import re` in the future.

**Comment by thadrien** [comment]
Or something else :
```
import re
try:
    info['pattern'] = re.match(cls.__pattern__, url).groupdict()
except Exception:
    pass
```

If re module is already imported, `import re` will do nothing. Otherwise, it will import re. Since this import is closer to the point where it will be used, there are less risks of forgetting it again.

**Comment by GammaC0de** [comment]
better is:
```python
except IndexError:
  pass
except Exception:
  raise
```

**Comment by thadrien** [comment]
:+1:

**Pull request merged**
