### PR TITLE
adapt PremiumTo Plugin from pyload 0.4.20

### PR DESCRIPTION
**Pull request by the-rene**
### Describe the changes

Updated the PremiumTo Plugin by using the code of pyload 0.4.20

### Is this related to a problem?
AFAIK no issue fot that is open

### CODE REVIEW

**Comment by the-rene** [comment]
Changed to draft. Downloading works, but the status in the queue shows this error on each downloaded link:
`failed cannot use a string pattern on a bytes-like object`

I might look into it on the weekend, but "works for me" right now.

**Comment by GammaC0de** [comment]
Hi,
Thanks for your contribution.

First of all, all PRs should be against the `develop` branch.
Second, I can see some incompatibilities that has not been addressed yet.

If you would like, you can change to a temporary password and send me credentials via email so I can migrate the plugin.

**Comment by the-rene** [comment]
Hi,
I'll remember to PR into develop branch next time ;)

I sent the currently valid api credentials for my premium.to account to you for testing, please let me know when you don't need them anymore. I'd appreciate if you migrate the plugin, you know the codebase the best :)

**Comment by GammaC0de** [comment]
Migration done

**Pull request closed without merging**
