### PR TITLE
[SimpleHoster] update

### LINKED ISSUE #1729: Reason for "Download failed | Fallback to free download | Download was already free"
I traced through the functions defined in UploadedTo.py, SimpleHoster.py and Hoster.py a bit to try and find out what is happening.
My log output is the following:

	06.08.2015 11:58:55 INFO      Download starts: http://uploaded.net/file/sdzkjtrh/File1.rar
	06.08.2015 11:58:55 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	06.08.2015 11:58:55 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
	06.08.2015 11:58:55 DEBUG     Redirected import module.plugins.internal.Account -> userplugins.internal.Account
	06.08.2015 11:58:55 DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	06.08.2015 11:58:55 DEBUG     HOSTER UploadedTo[10]: PROCESS URL http://uploaded.net/file/sdzkjtrh/File1.rar | PLUGIN VERSION 0.96
	06.08.2015 11:58:55 DEBUG     HOSTER UploadedTo[10]: Config option `fallback` not found, use default `True`
	06.08.2015 11:58:55 WARNING   Download failed: http://uploaded.net/file/sdzkjtrh/File1.rar | Fallback to free download | Download was already free
	06.08.2015 11:58:55 INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: http://uploaded.net/file/sdzkjtrh/File1.rar (pid:3)
	06.08.2015 11:58:55 INFO      HOOK UnSkipOnFail: No duplicates found

So the debug output `PROCESS URL http://uploaded.net/file/sdzkjtrh/File1.rar | PLUGIN VERSION 0.96` is obviously from the function `preprocessing` in `Hoster.py`. After the output the fuction `process` from `SimpleHoster.py` is called which calls the function `prepare` (also in `SimpleHoster.py`).
In this function the lines

    if not self.get_config('use_premium', True):
	                self.restart(nopremium=True)

obvious call the function `restart` from `Hoster.py` everytime we are doing a free download. The function `restart` tries to fallback to free which it already was, so it fails:

    def restart(self, reason=None, nopremium=False):
        if not reason:
            reason = _("Fallback to free download") if nopremium else _("Restart")

        if nopremium:
            if self.premium:
                self.retry_free = True
            else:
                self.fail("%s | %s" % (reason, _("Download was already free")))

        raise Retry(encode(reason))  #@TODO: Remove `encode` in 0.4.10

So this CAN'T work, right?

### PR DESCRIPTION
**Pull request by GammaC0de**
fix #1729

### CODE REVIEW

**Comment by 1337sup3rh4x0r** [comment]
I'll test and report back in 3 hours when the wait time is over :)

**Comment by 1337sup3rh4x0r** [comment]
Unfortunately this didn't fix it. First download works, the second generates the following output:

	3755	09.08.2015 14:47:28	INFO	Download starts: http://uploaded.net/file/2g2ogm0q/File0.rar
	3756	09.08.2015 14:47:28	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	3757	09.08.2015 14:47:28	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	3758	09.08.2015 14:47:28	DEBUG	HOSTER UploadedTo[11]: PROCESS URL http://uploaded.net/file/2g2ogm0q/File0.rar | PLUGIN VERSION 0.96
	3759	09.08.2015 14:47:28	INFO	HOSTER UploadedTo[11]: Updating file info...
	3760	09.08.2015 14:47:28	DEBUG	HOSTER UploadedTo[11]: File info: {'status': 2, 'url': u'http://uploaded.net/file/2g2ogm0q', 'size': 105906176.0, 'name': 'File0.rar', 'pattern': {'ID': u'2g2ogm0q'}}
	3761	09.08.2015 14:47:28	DEBUG	HOSTER UploadedTo[11]: Previous file info: {}
	3762	09.08.2015 14:47:28	INFO	HOSTER UploadedTo[11]: File name: File0.rar
	3763	09.08.2015 14:47:28	INFO	HOSTER UploadedTo[11]: File size: 105906176 bytes
	3764	09.08.2015 14:47:28	INFO	HOSTER UploadedTo[11]: File status: online
	3765	09.08.2015 14:47:28	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/file/2g2ogm0q | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
	3766	09.08.2015 14:47:28	INFO	HOSTER UploadedTo[11]: Processing as free download...
	3767	09.08.2015 14:47:28	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
	3768	09.08.2015 14:47:28	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3769	09.08.2015 14:47:29	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
	3770	09.08.2015 14:47:29	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3771	09.08.2015 14:47:29	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Challenge: 03AHJ_VuvCVIxozJd-RH6HatLytv0pXKDi1qRGGRniyo6RWhVNUfn5PWqZP0ePPilbYfLXYQNf1BG7LvV5zW_RqJvIF5vZfrZCr0EzSBLQm7G7OUENnvDqYYLg5hEG8or6F3GNoU_T1F5S0lA3YDMYWrtbATewb_ITHl-pw4F1A-fypFiNODiAIo2zvKtSR22b83KXpN8grdo7YW8IK6dRdIbEggQGNRgYUQ
	3772	09.08.2015 14:47:29	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3773	09.08.2015 14:47:29	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_VuvCVIxozJd-RH6HatLytv0pXKDi1qRGGRniyo6RWhVNUfn5PWqZP0ePPilbYfLXYQNf1BG7LvV5zW_RqJvIF5vZfrZCr0EzSBLQm7G7OUENnvDqYYLg5hEG8or6F3GNoU_T1F5S0lA3YDMYWrtbATewb_ITHl-pw4F1A-fypFiNODiAIo2zvKtSR22b83KXpN8grdo7YW8IK6dRdIbEggQGNRgYUQ', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3774	09.08.2015 14:47:29	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Second challenge: 03AHJ_VuvnJ8mP5ga2_8hVmn-a-Zv_gdsTEGrg-3Y99Woj2OPkXZXxWVVsCJc59CHCnh_xwlAC8oG1LCOJoff4mtZzKTIAUWEDZN9O77WI7PEeOyisBS9AzpgZ1SFCYSaImv7jCyptPQlxo1kKiw59gFNohFOUZ_K3bIHB0xlCzs2TeCUz3PLZx3ZvqqiWyF_NMzcYeeAB43hqMU_GDldHLolDcELhcuZP6w 
	3775	09.08.2015 14:47:29	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_VuvnJ8mP5ga2_8hVmn-a-Zv_gdsTEGrg-3Y99Woj2OPkXZXxWVVsCJc59CHCnh_xwlAC8oG1LCOJoff4mtZzKTIAUWEDZN9O77WI7PEeOyisBS9AzpgZ1SFCYSaImv7jCyptPQlxo1kKiw59gFNohFOUZ_K3bIHB0xlCzs2TeCUz3PLZx3ZvqqiWyF_NMzcYeeAB43hqMU_GDldHLolDcELhcuZP6w'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
	3776	09.08.2015 14:47:29	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'action': 'usercaptchaguthaben', 'source': 'pyload', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3777	09.08.2015 14:47:30	INFO	HOOK Captcha9Kw: 565 credits left
	3778	09.08.2015 14:47:30	DEBUG	HOOK Captcha9Kw: LOAD URL http://www.9kw.eu/grafik/servercheck.txt | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3779	09.08.2015 14:47:30	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={} | req=None | decode=True | multipart=False | post={'file-upload-01': '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAA5ASwBAREA/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oACAEBAAA/APf6K4b4nWXjO80SNvB9+ltJDukuI14lmAAKhDg88Hjvnr2K/D/xvL4gtBpuuxCw8R24xPZyfK8gAH7wLgcHPTtXcVBaX1rfxNLZ3MVxGrlGaJwwVgcFTjoQeo6ip6KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK5T4jRSp4Lv9Rtbhra+06Jrq2nXGUZVPqDnIJGO+a+WL34g6/d+LrPxW8sKanAoCPHGVUgZGCM85BIPrn617PoXxl1vTrDT7vxpoE1tplzlV1KJPvtjIOz+7juM+1Utb8cT/Djx3Fe2Lrd+FfEG2+kUoSVLYDvH0IbGDg8H0B5r2nRtb03xDpcWpaTeR3VpKPlkT+RB5B9jgir9FFFFFFFZ+r67pWg263Grahb2UTnarzyBQT6DNWLK9ttSsoryznSe2lXdHIhyGHqKsUUUUUUUUUUUUUUUUUUUUUUVyvxKleH4a+InjZVb7DIoLDPUY49+ePfFfMVz4Zsm+D1l4jtjvvY9SeC62j7qkDaD9MdR/e/L3DxXCbz9nCPZIVC6VayZJIyFCHHGM5x6Y/CvnBtTvNW07RtAdoxb20riHOOsj5OT169q9s13wvrHwcit/E/hi6lm08lF1TTXLNGT/eBA4XqMnkEjqDivZfDetxeJPDlhrMMTwx3cQkEbkEr7cVq0UVBe3cVhY3F5NuMVvE0r7Rk4UZOB68Vzvgfx1p/j3Trq/022uYIYJvJIuAoYnAPQE9iO9cf40+L2oeDfHUGlXmghdIbaTdM5LyqerJ2wDxg5PFVPiJ8a7zwjr0emado8E6NHFcLdTSkrLGwJ+VRj/vrJHB4rkvGfj9vHXw4mGr+Gr+wePbcWt8sLGB23bcBiOAc+v6gV6H8CvEA1j4ew2bMDPprm3b/AHeq/ocfh65r06iiiiiiiiiiiiiiiiiiiiiiszxFpf8AbnhvUtL3BTd20kIJGQCykDivFvDvwr8Tv4B8ReDb9orJnu7e5guSd8U3GWUcZ42rn3/HPc61oN3pnwIvNEumie6tNKMbmEsVYoM8Z5PT2/AV8mz22y1s5x92ZWBOOAytgj8tp/GvQPGWveOtB8Np4M8QSiawkVZba7+bdLEMFQHyMr/suMjIz0GNrVviD4k+H3hTQfC1gDaXa2S3E00yK7rvYsFUYxwMg5B+uRW9pGpfHH7EurCGO7tnYMlrMsIZ1I6jGCF+prpfCXjq9+Jema34av4ZNF1qCEqZrSVkwckZU5ypBxkZORnsSBwEXw3+Jdpc3umza4bXTTCXlvJbxvKKbidoPYk8kce59cTwV4z1Xw746Gm6zrs1zps0jW90/wBs82MbgB5gbJBIwOR6V0/wf1QeDfiLq3hbUJlit7onyHY4VmU/JjPqpP8ALvXWftDSaa/gSJZZI2vo7yPyVDLvXIbOR1wQD+IHpXjPjVm1Xwr4T11Isp9jNhNIzFmMsTHqT2KkEY96+lfBGt6P448B24QRzxeQLa7gZQNrhQGBA4GevHrXknw6uR4H+Nmq+FLUiSwuZmhU78lcAsmc4yRnB/HrX0XRRXN+IPHegeF5Uj1a6+zs+dmQPmx1xzWXY/FrwhqN5HaWuoF55WCogAySfxrrZNRt4bUXMrFIiM5auGk+NnguPUZLM3suEUN5wVfLJz0B3Zz+FdD4d8c6H4pmki0q4aZowC3GMZ/GuiBzQWApaKM0UUZozRmiiiiiiimTQxXEEkE8aSwyKUeN1DKykYIIPUEdq8j1b4E6Pdy6wtqphgnjM2nqjlRbXBGCMfxKdq9emSPQ1w6+L7DWPBMvhLxcjab4m0RSNNuJI9v7xB8qEk4UnaFJbCkYOc1yfijxBJ8RrC31FrVF17T4Nt55YGbuIY/egDHK91GcDnoDjtvBOka/8Q/DiLN8TJ7MRobc6dEpyEORtYBkzkDj73BxxWTqPwh8deC7u5vtFvBLGsbg3lrN5LiPnOckEcDkAnk8Z61l+B5NK8ZazLaeP/EeoLDbxg2qTXZWPcDgqcg445429DWN408MWelzvd+HlvLvQIn+zjU5VxHcTbmJCN0YADGR/dJr2Sx+FugfEbQdG8SpqOo2l5JawxzSIwbeY12Z5HDHAyRxx65JS+/Zzsrq/ilXxNqDQY/fC4RZJHPs3AH4g1b8KfCe80K+1Xw9qaxap4Qv1EgLPskSUYw3GCDgYyP/ANeXpfgPxn8MfFdxd+F7aHWNKusxrBLMUKKSCC3bI6bh1x2rOuvg742bxdB4mtriwF9POb24Vp2RYZGcsUBUElcHGRX0JD5nkx+cEEu0b9hyu7HOM9qfRXn/AMU/DWlap4WvtQu7OOW4tYHaJ26qdvUflXh3wHtYLv4i7ZwCqWkjgH1BWvqe7WFbKTdGGREJC/hXxPd3UOu+NzP5OyG7vVzGewLAYr7N0nR9O0HT0gtLdIY4kAyB0AFeYar8Zrm81280TwtpZvrmJWCSOcLuHB4JHANW4PjE2m6lBp/ijS5NMkkQMrkhwxzjoua7bxh4rh8J+F7jW3gadIwu1EOC2SB/WsL4e/EmHxzY30kcBiuLUbmhPYHOOffFctpvxz+2eMY9DfS3USXRtt+4cHdjNdj4++I1p4HtbR3t2uprhwoiRwCBzzzWXF8Urq2nRdX0G5sIpWCxPkS7ie3y5xXoAv4PsH2yRwkIXezHsOtee2vxQfX9cvLLQLF5rS04e7P3d3pjr2NUPCfxusda8RjRr+1ktZWcxpITkMwPTjp3r12iiiiiiiiuK8a/C3w344f7TfQyW+oBQovLZtrkDoGByGH1GfQiua0H4BaDoev22pjU7+5W3cukLkJk87csuDxx9cehxV/xB8EPDGr6kuo6e9zot2H3s9i+AW45CnhT/u4qtF8DNMaVJb/xLr968biRPMuRgMOh6Z49iK6D/hVHg2TV31W70eG6u5MFzKMRlgACfLXCZOMnjqTXSXWh6VeaQ2k3GnWz6cy7fs3lgRgdeAOnPpU9hp9npVjFZafaw2trECI4YUCKuTk4A9SSfqas0UUUUUVyvxGbZ4B1cnnNu4/8dNfMnwls9Sv/ABoLfSr5bO4aBv3rRbwBkZGMivpQeHtYt9IIu9be4mWJt7KhUNwe2a+Xvh1bw3PxD02KeNZE84kqwyMgEivq3x3PLbeCdWmt3ZJBbvhlOCPlNeJfs9aba3mv6hqdwWe7iXYpLdQ3JJHfkVq/tFiwjttKKCJb/fngAPs5/HGaqzavf65+zheTX6TeZbukSyykkyqGX5sn61P+zZHBnXWErNMViDxlOFGWwc981wvxDuLbw/8AF+a8sbdAlvLHN5afKC2Mn8zXqfxF8JS+O9IsLjT2hXUY4lkjDEAsMfdz25Oa87fxl4z8H3lpp/iO0aSzt32EyRnMg9nPWvR/HnjaG++D0mpaFKFjlKQuCM4DEBgffBryz4V654n0G8kXSNHlvrS9IV12HaWHAO7BwBk1hp4Q8Wz+IiYdJvbW5lnZkkaNkCEkn72OB719p0UUUUUUUUUUUUUUUUUUUUUV86fFn4vSXZ1LwvpkDReTcSW1zNIBzsYqdvXg4NebfDrxFceGfGNreW1s1y8n7kxr94gkdPfivoDWviZqx0m4jsfCWpi5eMqhmRQuT64avmyN9W8Ka7BdPC9tdxnzFVwOQf8AJr6Q+HfjuP4maJqGkajaCKZI9kgUnayMCOD1zwa4TRfCPin4aeN5dRtrIXNgUlO2NiR5e4YHPVsdPxqnrWheMviv4jhurnR10+OBNoaRjtZd34817hc+FLez+Hc/h+0gDolsVRMZyQOOvvXz/wCBpPHHgWXUEsfDcs0t2qq+/grtz0/OuV1vwz4qk1F7zUdKuklvJyF385diSFHNem2tj8SZNZ0HUIdGaBEg8pxuOwKD/wAtPQ8dqufEPxBeeLIJ/C6aFO2px7SJQg2gbh82c5x1rsPDPwstU+GDeG9XYyNOxmZgcbHOCMeuCK8mX/hL/grrNyVtxc6YzYV3/wBW+enPUHHXFeyfDPxhqnjixlv9R0uK0iVsQsnIkHc5PvXolFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf/Z', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'captchapermin': 9999, 'case-sensitive': 0, 'prio': 0, 'confirm': False, 'source': 'pyload', 'maxtimeout': 900, 'captchaperhour': 9999, 'selfsolve': False, 'max_len': 50, 'min_len': 2, 'base64': '1', 'numeric': 0, 'action': 'usercaptchaupload', 'phrase': 0, 'pyload': '1', 'mouse': 0, 'math': 0, 'oldsource': 'UploadedTo'} | ref=True | just_header=False
	3780	09.08.2015 14:47:30	DEBUG	HOOK Captcha9Kw: NewCaptchaID ticket: 56915334 | tmp/captcha_image_UploadedTo_44920.jpg
	3781	09.08.2015 14:47:30	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'info': '1', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'source': 'pyload', 'action': 'usercaptchacorrectdata', 'id': u'56915334', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3782	09.08.2015 14:47:36	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'info': '1', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'source': 'pyload', 'action': 'usercaptchacorrectdata', 'id': u'56915334', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3783	09.08.2015 14:47:42	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'info': '1', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'source': 'pyload', 'action': 'usercaptchacorrectdata', 'id': u'56915334', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3784	09.08.2015 14:47:48	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'info': '1', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'source': 'pyload', 'action': 'usercaptchacorrectdata', 'id': u'56915334', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3785	09.08.2015 14:47:54	DEBUG	HOOK Captcha9Kw: LOAD URL https://www.9kw.eu/index.cgi | cookies=True | get={'info': '1', 'apikey': u'53FQ1FLHU5BWAIRHU3', 'source': 'pyload', 'action': 'usercaptchacorrectdata', 'id': u'56915334', 'pyload': '1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3786	09.08.2015 14:47:55	INFO	HOOK Captcha9Kw: Captcha result for ticket 56915334: inbeaud house
	3787	09.08.2015 14:47:56	INFO	CAPTCHA UploadedTo[11]: ReCaptcha | Captcha result: inbeaud house
	3788	09.08.2015 14:47:56	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Result: inbeaud house
	3789	09.08.2015 14:47:56	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/io/ticket/captcha/2g2ogm0q | cookies=True | get={} | req=None | decode=True | multipart=False | post={'recaptcha_challenge_field': u'03AHJ_VuvnJ8mP5ga2_8hVmn-a-Zv_gdsTEGrg-3Y99Woj2OPkXZXxWVVsCJc59CHCnh_xwlAC8oG1LCOJoff4mtZzKTIAUWEDZN9O77WI7PEeOyisBS9AzpgZ1SFCYSaImv7jCyptPQlxo1kKiw59gFNohFOUZ_K3bIHB0xlCzs2TeCUz3PLZx3ZvqqiWyF_NMzcYeeAB43hqMU_GDldHLolDcELhcuZP6w', 'recaptcha_response_field': u'inbeaud house'} | ref=True | just_header=False
	3790	09.08.2015 14:47:57	DEBUG	HOSTER UploadedTo[11]: Config option `fallback` not found, use default `True`
	3791	09.08.2015 14:47:57	WARNING	Download failed: File0.rar | Parse error: Free download link not found | Plugin may be out of date
	3792	09.08.2015 14:47:57	INFO	HOOK UnSkipOnFail: Looking for skipped duplicates of: File0.rar (pid:3)
	3793	09.08.2015 14:47:57	INFO	HOOK UnSkipOnFail: No duplicates found 

Also the plugin doesn't wait for 3 hours like it should but tries immediately. I think the time is not read right as I stated in #1477

**Comment by 1337sup3rh4x0r** [comment]
By the way, three hours later when I manually restart the download, it works and the output looks like this:

	3879	09.08.2015 19:31:23	INFO	Download starts: File0.rar
	3880	09.08.2015 19:31:23	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	3881	09.08.2015 19:31:23	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
	3882	09.08.2015 19:31:23	DEBUG	HOSTER UploadedTo[11]: PROCESS URL http://uploaded.net/file/2g2ogm0q | PLUGIN VERSION 0.96
	3883	09.08.2015 19:31:23	INFO	HOSTER UploadedTo[11]: Updating file info...
	3884	09.08.2015 19:31:23	DEBUG	HOSTER UploadedTo[11]: File info: {'status': 2, 'url': u'http://uploaded.net/file/2g2ogm0q', 'size': 105906176.0, 'name': 'File0.rar', 'pattern': {'ID': u'2g2ogm0q'}}
	3885	09.08.2015 19:31:23	DEBUG	HOSTER UploadedTo[11]: Previous file info: {} 
	3886	09.08.2015 19:31:23	INFO	HOSTER UploadedTo[11]: File name: File0.rar
	3887	09.08.2015 19:31:23	INFO	HOSTER UploadedTo[11]: File size: 105906176 bytes
	3888	09.08.2015 19:31:23	INFO	HOSTER UploadedTo[11]: File status: online
	3889	09.08.2015 19:31:23	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/file/2g2ogm0q | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
	3890	09.08.2015 19:31:24	INFO	HOSTER UploadedTo[11]: Processing as free download...
	3891	09.08.2015 19:31:24	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
	3892	09.08.2015 19:31:24	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3893	09.08.2015 19:31:24	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Key: 6Jxqu78SAAAAAPgsTYF3UlGf6zFQCNiPMenuyHV1
	3894	09.08.2015 19:31:24	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Jxqu78SAAAAAPgsTYF3UlGf6zFQCNiPMenuyHV1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3895	09.08.2015 19:31:24	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Challenge: 03AHJ_Vuu-I88oirCmSmViaLwoytzH555W7vKCIKZRPqlQPtLJH0qjnpopRx629UCGMnB_itAJ4qono9dba6K_4Z7db8RPLUWGwFhHLw9RhOo85gqiiYYdymKAW99_gO9CLuNApHSap6gzinS4lg-0QwFImwdDJlyob65YTdwCEUpjm_yz4ZORt7rDMZlsu0bRRlshdZiCBfyvfPYQJMfqTDDuLlU4UnGgIg
	3896	09.08.2015 19:31:24	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3897	09.08.2015 19:31:24	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vuu-I88oirCmSmViaLwoytzH555W7vKCIKZRPqlQPtLJH0qjnpopRx629UCGMnB_itAJ4qono9dba6K_4Z7db8RPLUWGwFhHLw9RhOo85gqiiYYdymKAW99_gO9CLuNApHSap6gzinS4lg-0QwFImwdDJlyob65YTdwCEUpjm_yz4ZORt7rDMZlsu0bRRlshdZiCBfyvfPYQJMfqTDDuLlU4UnGgIg', 'type': 'image', 'k': u'6Jxqu78SAAAAAPgsTYF3UlGf6zFQCNiPMenuyHV1'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
	3898	09.08.2015 19:31:24	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Second challenge: 03AHJ_VuufBOzoAnM_hqvF3Q_-YDt1pCiCyAmUwHq9BydIJfwyAfYtq58kfEPB_yJH3RR8UN8tAwz-0QiTj4Ict5jSUE0TBlrGnGoP4YWVb2zJWWl8zwKSQwx9VTL2GP6C5mc68nBeo5XY0xcUBkz8IKDyEQz-C_1mmZdZSBjd0SnCliXPIzS0jgDL7MEJ3MLiMqiqdiUJiaUBIY2c7lS-jPobJ4ky-ythNA
	3899	09.08.2015 19:31:24	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_VuufBOzoAnM_hqvF3Q_-YDt1pCiCyAmUwHq9BydIJfwyAfYtq58kfEPB_yJH3RR8UN8tAwz-0QiTj4Ict5jSUE0TBlrGnGoP4YWVb2zJWWl8zwKSQwx9VTL2GP6C5mc68nBeo5XY0xcUBkz8IKDyEQz-C_1mmZdZSBjd0SnCliXPIzS0jgDL7MEJ3MLiMqiqdiUJiaUBIY2c7lS-jPobJ4ky-ythNA'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
	3900	09.08.2015 19:31:41	INFO	CAPTCHA UploadedTo[11]: ReCaptcha | Captcha result: recognition elecytr
	3901	09.08.2015 19:31:41	DEBUG	CAPTCHA UploadedTo[11]: ReCaptcha | Result: recognition elecytr
	3902	09.08.2015 19:31:41	DEBUG	HOSTER UploadedTo[11]: LOAD URL http://uploaded.net/io/ticket/captcha/2g2ogm0q | cookies=True | get={} | req=None | decode=True | multipart=False | post={'recaptcha_challenge_field': u'03AHJ_VuufBOzoAnM_hqvF3Q_-YDt1pCiCyAmUwHq9BydIJfwyAfYtq58kfEPB_yJH3RR8UN8tAwz-0QiTj4Ict5jSUE0TBlrGnGoP4YWVb2zJWWl8zwKSQwx9VTL2GP6C5mc68nBeo5XY0xcUBkz8IKDyEQz-C_1mmZdZSBjd0SnCliXPIzS0jgDL7MEJ3MLiMqiqdiUJiaUBIY2c7lS-jPobJ4ky-ythNA', 'recaptcha_response_field': 'recognition elecytr'} | ref=True | just_header=False
	3903	09.08.2015 19:31:42	INFO	HOSTER UploadedTo[11]: Downloading file...
	3904	09.08.2015 19:31:42	DEBUG	HOSTER UploadedTo[11]: DOWNLOAD URL http://am4-r1f5-stor05.uploaded.net/dl/c3e7fa2f-a2f1-4759-8fc7-d2179761300a | cookies=True | get={} | disposition=True | post={} | ref=True
	3905	09.08.2015 19:31:42	DEBUG	Content-Disposition: File0.rar 

I really think the issue at hand here is that the wait time is wrong or a wait pattern is not recognized. The output of uploaded.net is misleading though. It states  ``You have reached the max. number of possible free downloads for this hour`` but the real wait time is three hours. So somehow UploadedTo.py would need a hardcoded wait time as soon as the pattern above is detected. But I don't know how to implement that.

**Comment by GammaC0de** [comment]
@1337sup3rh4x0r this is a fix for issue #1729 only not for #1477.
Also, please do not post here, post in the relevant issue thread, thanks.

**Pull request merged**
