### PR TITLE
[UptoboxCom] account update

### PR DESCRIPTION
**Pull request by benbox69**
The UptoboxCom account plug-in is not working since change has been made in version 0.11...
I tried to make this update conform with the using of XFSAccount... but the login action is completely different because I am using the answer of the ajax request made by Uptobox to login a user and I am not parsing the HTML content to fill a form.
This version is tested and works very well...

### CODE REVIEW

**Comment by vuolter** [comment]
Check https://github.com/pyload/pyload/commit/bd89c11fd385bdbff1f5eb1d7c7d534e6d728946.

**Comment by benbox69** [comment]
Not sure to understand what's wrong with my commit.

**Comment by vuolter** [comment]
The new XFSAccount version parses json object as well, so I just reverted the UptoboxCom as it was before.

**Comment by benbox69** [comment]
Ok I understand but it's not working...
You get a 502 error on line 161 request (XFSAccount) because the login and password are needed... That's why I changed the login action.

**Comment by vuolter** [comment]
@benbox69 Checking...

**Pull request closed without merging**
