### PR TITLE
[TurbobitCom] fix premium download

### PR DESCRIPTION
**Pull request by Web-Eye**
### Describe the changes

Since a few days Turbobit.Net lost the premium validation after the the first parallel downloads in the queue were finished.

### Is this related to a problem?

Maybe an issue from #2211 

### Additional references

Pleas revisit the pull-request, it might be not the optimal solution.

### CODE REVIEW

**Comment by GammaC0de** [comment]
Are you sure it's because #2211?
Would you like to share your account so I can check this?

**Comment by Web-Eye** [comment]
@GammaC0de 

> Are you sure it's because #2211? 

I'm not sure, but it seems that my problems appears since https://github.com/pyload/pyload/commit/5c67a158ca3132d8bf706f5f24e2f1a8afb4a7a9 and in this commit is a change in account.py, but I'm not to much in, that I can assess this change....

> Would you like to share your account so I can check this?

How could I provide you, my credentials?

Cheers,
WebEye

**Comment by GammaC0de** [comment]
Please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
@Web-Eye Please test.

**Comment by GammaC0de** [comment]
On Thursday, March 23, 2023 at 05:59:48 PM GMT+2, WebEye ***@***.***> wrote:  
 
 


Wow, that was deep!
However, seems to be fixed.

-Restarted pyload to get latetest updates
-start downloads
-no lost of premium status, after finishing the first parallel downloads.

Thanks a lot @GammaC0de

**Pull request merged**
