### PR TITLE
Few plugin changes

### PR DESCRIPTION
**Pull request by Arno-Nymous**
[ShareLinksBiz] Speed up link parsing by cascading through all available container types.
[Captcha.py] Change string formatting to `.format()` here as well. Also fixes an `TypeError`
occuring on [line 106](https://github.com/pyload/pyload/blob/aa6e9a25714fe429cffc02f44b0f73a673ed85f8/module/plugins/internal/Captcha.py#L106).

**Please mind to raise any version numbers when merging into the project since I don't use the update manager in my fork.**

### CODE REVIEW

**Comment by vuolter** [comment]
Why you closed it?

**Comment by Arno-Nymous** [comment]
Sorry, deleted it accidentally with some other branches I didn't need. Will create a new one and make a new pull request immediately.

**Comment by GammaC0de** [comment]
This PR can be reopened and merged, you know, the changes are not deleted..
Although, `.format()` is not compatible with python 2.5 so changes has to be made to the PR...

**Comment by Arno-Nymous** [comment]
I cannot reopen it since I deleted the whole branch. Have to merge the changes from this commit with the  current stable and open a new PR.

**Comment by GammaC0de** [comment]
:+1:
Please remember not to use `.format()` as it is not compatible with python 2.5 and many NAS boxes still use python 2.5

**Comment by Arno-Nymous** [comment]
Please see the new pull request here https://github.com/pyload/pyload/pull/2439.

**Pull request closed without merging**
