### PR TITLE
Fix support for the 'Path Prefix' option on the default template

### PR DESCRIPTION
**Pull request by gimco**
I`ve replaced all the absolute uri on the default template to use the 'url' filter to take care of the "Path Prefix" option of the webinterface.

### CODE REVIEW

**Comment by I-RiX-I** [comment]
Will this require rework of the new bootstrap webinterface?

**Comment by gimco** [comment]
If you're referring to the pull #1006, yes, It will require rework on the new webinterface.
If the legacy pyload webinteface will be deprecated in favor of the new bootstrap, you should reject this pull and I'll send a new pull with the modifications on the (new official) bootstrap theme.

**Comment by I-RiX-I** [comment]
Yes indeed, seems like that needs a fix too, its paths are hardcoded.

**Comment by I-RiX-I** [comment]
I reworked some things: (unfinished)

https://github.com/pyload/pyload/pull/2015

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload/pull/3077

**Pull request closed without merging**
