### PR TITLE
[ExtractArchive] [AntiVirus] fix send2trash

### LINKED ISSUE #1351: send2trash not working on OSX
The integration of send2trash broke extracting archives on Mac OSX. 

send2trash is installed but not working. Because of that months old bug of "pluginsettings not saved" bug in pyLoad the option get's activated after every download again. So i can't turn it off. (Maybe it should be turned off by default?)

```22166 13.04.2015 12:40:32 ERROR ExtractArchive: test.part18.rar | Unknown error | global name 'send2trash' is not defined 
22167 13.04.2015 12:40:32 ERROR ExtractArchive: test.part18.rar | Extract failed```

The archives will be extracted, but not deleted and the hooks that would be called after extraction won't work because the extraction fails.

### PR DESCRIPTION
**Pull request by GammaC0de**
fix #1351

### CODE REVIEW

**Comment by vuolter** [comment]
@GammaC0de `import send2trash` is called on `setup`, why calling it again should solve #1351?

**Comment by GammaC0de** [comment]
Hi,
Since `import send2trash` is called on `setup` and not globally as all other imports, it is relevant only for `setup`
Calling `send2trash`  at `scan` or `_extract` cases an unknown function exception (I've verified that)

Since you cannot import send2trash globally, the solution is to import it on `scan` and `_extract` after you know `trashable` is True so its safe to import `send2trash`

**Comment by vuolter** [comment]
You're right: https://github.com/pyload/pyload/commit/711621f3d3a59f7ec5c2684dfac921e2c5902563
Thanks!

**Comment by GammaC0de** [comment]
:+1:

**Pull request closed without merging**
