### PR TITLE
[DlFreeFr] Fix some long url

### PR DESCRIPTION
**Pull request by nmss**

### CODE REVIEW

**Comment by GammaC0de** [comment]
Increase version please

**Comment by nmss** [comment]
Sorry for the version, it's done now

I just undo a part of my last changes, not everything
- the main change in the previous commit was the `process` function, it's still good
- the other change to `handle_free` was because I thought it was simpler, but it was also bugged so I'm reverting this part

**Comment by Exceen** [comment]
Didn't really fix the issue when downloading from share-online.biz. It still doesn't find the direct link and therefore uses the free download.

**Comment by GammaC0de** [comment]
@Exceen share-online.biz is totally different hoster it has nothing with DlFreeFr, if you have issues with it please open a new issue.

**Pull request closed without merging**
