### PR TITLE
[UpleaCom]  fix file size calculation and Set DISPOSITION to False (temp)

### LINKED ISSUE #1380: uplea plugin (still) broken
Hi again,

sorry but inspite of #1369 and #1375, uplea is still not working; now it's back with downloading the HTML download page...
24	26.04.2015 23:29:20	INFO	Download finished: *****
23	26.04.2015 23:29:02	INFO	Download starts: ****

The resulting file has correct name but is 14KB big; expected size if around 350MB

### PR DESCRIPTION
**Pull request by GammaC0de**
fix #1380

### CODE REVIEW

**Comment by JeanMars** [comment]
Hi,

I've just manually updated the non commited 0.09 to my NAS; this is better, the (real) file is downloaded but the name is not correct, actually it is the file id at uplea.com

**Comment by GammaC0de** [comment]
PR updated, please try now.

**Comment by JeanMars** [comment]
Works now; many thanks :-)

**Comment by GammaC0de** [comment]
:thumbsup:

**Pull request merged**
