### PR TITLE
Updated Links on Info-Page

### PR DESCRIPTION
**Pull request by Burnout5151**
Updated Links on Info-Page

### CODE REVIEW

**Comment by Burnout5151** [comment]
Ah, sorry, I just saw that @Gutz-Pilz  already commited something like this in #2071 
However my commit removes the link to the Forum and IRC-Chat as well, because they linked to the currently non-functional pyload.org.

**Comment by Burnout5151** [comment]
Hi @vuolter , thanks for your work and time :-)
I think the classification as enhancement is wrong: Before the commit the links were broken, now they work again -> This is a Bugfix.
And as a bugfix it should be merged now and not in the upcoming version.

Greetings
-Burnout

**Comment by vuolter** [comment]
@Burnout5151 Historically, only plugin changes are merged in stable branch.

**Comment by Burnout5151** [comment]
Hi  @vuolter , the software-versioning pattern I've seen in wide use is MAJOR.MINOR.RELEASE (_e.g. 0.4.9_).
So: 
1. major changes that may even break compatibility should count up the major _ e.g. 1.0 _
2. minor changes that bring new features should count up the minor _ e.g. 0.5 _
3. bugfixes/trivial changes should be placed in a new release number _ e.g. 0.4.10 _

The changes you are currently working on are at least a minor-bump, probably a major.
However, I think there should also be a bugfix-release 0.4.10 with this and other fixes.

Greetings
-Burnout

**Comment by Burnout5151** [comment]
Hi @vuolter , I took a look again at the [Milestone](https://github.com/pyload/pyload/milestones) and there clearly is a 0.4.10 Release scheduled. As I have laid out in the last post, I considered this to be a bugfix release. If 0.4.10 will happen, then I think this pull request should be assigned to that release.

Greetings
-Burnout

**Comment by GammaC0de** [comment]
@Burnout5151 Actually, v0.4.10 was renamed to v0.5 so this PR is scheduled for next release..

**Comment by GammaC0de** [comment]
Fixed.

**Pull request closed without merging**
