### PR TITLE
[internal/XFSHoster.py] Add captcha pattern for Recaptcha and Solvemedia

### PR DESCRIPTION
**Pull request by joberreiter**
Fixes the 'first argument must be string or compiled pattern' of #1852, #1859 and #1865.

### CODE REVIEW

**Comment by vuolter** [comment]
:+1:

**Comment by joberreiter** [comment]
@vuolter, @GammaC0de:
Is it incorrect to set the captcha patterns for Recaptcha and Solvemedia globally in XFSHoster.py?
Why is #1902 better?

**Comment by GammaC0de** [comment]
although both solutions works, #1902 gets the patterns from `captcha\ReCaptcha.py` and `captcha\SolveMedia.py` which is better because the patterns resides only in one place and if they will change in the future, you only have to change them in one place so there is no chance that you will forget to change them in other places

**Comment by vuolter** [comment]
@joberreiter  Totally agree with @GammaC0de , so I just merged #1902 .

**Comment by joberreiter** [comment]
I see and agree with you -- haven't noticed that those are already set in the captcha plugins.
:thumbsup:

**Pull request merged**
