### PR TITLE
[New Hoster] androidfilehost.com

### PR DESCRIPTION
**Pull request by zapp-brannigan**
Another plugin for downloading android-stuff.

### CODE REVIEW

**Comment by stickell** [comment]
Androidfilehost always publishes the MD5 checksum. Use the `HASHSUM_PATTERN` to get it.

**Comment by zapp-brannigan** [comment]
Ok, i've added the HASHSUM_PATTERN. But how to trigger the check after downloading?
```
02.02.2015 11:08:50 INFO      Download starts: https://www.androidfilehost.com/?fid=95916177934519691
02.02.2015 11:08:50 DEBUG     AndroidfilehostCom: File info (BEFORE): {}
02.02.2015 11:08:52 DEBUG     Finished Info Fetching for AndroidfilehostCom
02.02.2015 11:08:53 DEBUG     AndroidfilehostCom: File info (AFTER): {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d', 'size': 7444889.6}
02.02.2015 11:08:53 DEBUG     AndroidfilehostCom: File name: 1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip | File size: 7444889
02.02.2015 11:08:53 DEBUG     AndroidfilehostCom: File status: online | File info: {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d', 'size': 7444889.6}
02.02.2015 11:08:54 DEBUG     AndroidfilehostCom: File info (BEFORE): {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d', 'size': 7444889.6}
02.02.2015 11:08:54 DEBUG     AndroidfilehostCom: File info (AFTER): {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, 'size': 7444889.6, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d'}
02.02.2015 11:08:54 DEBUG     AndroidfilehostCom: File name: 1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip | File size: 7444889
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: File info (BEFORE): {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, 'size': 7444889.6, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d'}
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: File info (AFTER): {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, 'size': 7444889.6, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d'}
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: File name: 1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip | File size: 7444889
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: File status: online | File info: {'status': 2, 'name': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip', 'url': u'https://www.androidfilehost.com/?fid=95916177934519691', 'pattern': {'H': u'8e947c5689c3c2e2b66bb76c8859d48d', 'S': u'7.1', 'U': u'MB', 'T': u'md5', 'N': u'1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip'}, 'size': 7444889.6, u'md5': u'8e947c5689c3c2e2b66bb76c8859d48d'}
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: Handled as free download
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: Waitingtime: 8 seconds
02.02.2015 11:09:04 DEBUG     AndroidfilehostCom: fid: 95916177934519691
02.02.2015 11:09:06 DEBUG     AndroidfilehostCom: DL-URL: http://tx2.androidfilehost.com/dl/Z8C-SFXCMyXnpvdFA2bbIw/1422875345/95916177934519691/1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip
02.02.2015 11:09:06 DEBUG     AndroidfilehostCom: Mirror Host: tx2.androidfilehost.com
02.02.2015 11:09:12 DEBUG     Content-Disposition: 1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip
02.02.2015 11:09:19 INFO      Download finished: 1032_Retail_BR_Kernel_3.4.42-g48d3b85.zip
02.02.2015 11:09:19 INFO      Package finished: ffff
02.02.2015 11:09:19 DEBUG     All downloads processed
02.02.2015 11:09:19 DEBUG     All downloads finished
```

**Comment by stickell** [comment]
Do you have the Checksum plugin enabled?

**Comment by zapp-brannigan** [comment]
My plugin was disabled (shame on me :D)
But after enableing and redownloading there were no log entrys regarding checksum checking. The log looks like above.
```
Checksum - "Checksum":
        bool activated : "Activated" = True
        int wait_time : "Time to wait before each retry (seconds)" = 1
        fail;nothing retry_action : "What to do if all retries fail?" = fail
        fail;retry;nothing check_action : "What to do if check fails?" = fail
        bool check_checksum : "Check checksum? (If False only size will be verified)" = True
        int max_tries : "Number of retries" = 2
```

```
02.02.2015 12:47:05 INFO      Aktivierte Plugins: Captcha9Kw, CaptchaTrader, Checksum, ClickAndLoad...
```

**Comment by stickell** [comment]
Let's wait for @vuolter who has implemented this feature

**Comment by vuolter** [comment]
Now searching the (old) new Checksum.py in my git... XD

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/65c83f937b3a8f819d89cae9204ac12cb6ba1deb

**Pull request merged**
