### PR TITLE
[SimpleHoster] fix #1854

### LINKED ISSUE #1854: UploadedTo "no such group" error
first Problem is: I have entered a valid premium Account but Uploaded still asks for Captcha.
When I solve it - this happens:
```
pyLoad 0.4.9 Debug Report of UploadedTo 0.97 

TRACEBACK:
 Traceback (most recent call last):
  File "/root/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/pyload/module/plugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/pyload/module/plugins/internal/Hoster.py", line 179, in _process
    return self.process(self.pyfile)
  File "/root/pyload/module/plugins/internal/SimpleHoster.py", line 284, in process
    self.handle_free(pyfile)
  File "/root/pyload/module/plugins/hoster/UploadedTo.py", line 80, in handle_free
    self.check_errors()
  File "/root/pyload/module/plugins/internal/SimpleHoster.py", line 362, in check_errors
    errmsg = m.group(1).strip()
IndexError: no such group
 

FRAMESTACK:

Frame preprocessing in /root/pyload/module/plugins/internal/Hoster.py at line 184
                        self = <Hoster UploadedTo>
                        args = (<DownloadThread(Thread-2, started daemon 140231843899136)>,)
                      kwargs = {}

Frame _process in /root/pyload/module/plugins/internal/Hoster.py at line 179
                        self = <Hoster UploadedTo>
                      thread = <DownloadThread(Thread-2, started daemon 140231843899136)>

Frame process in /root/pyload/module/plugins/internal/SimpleHoster.py at line 298
                      pyfile = PyFile 915: 01ruul.part1.rar@UploadedTo
                        self = <Hoster UploadedTo>

Frame handle_free in /root/pyload/module/plugins/hoster/UploadedTo.py at line 80
                      pyfile = PyFile 915: 01ruul.part1.rar@UploadedTo
                   challenge = u'03AHJ_Vuv20YFI-4ZjeBc1dhKidI1P_PKtN4MnSzA0nyGFcNmTt1tj7A088nZBOeQKU8_1Loh9F-POobLkQWDHVOOTzC_pubOBEM3n2fGUSV5S47vgQD7AFHXdViEeM4uUJWHPJXwHTbbbhVbE-EkkcD7zhrEUs5My1WZUUb2ZjdRYbW_SSkQ6VgiuxIodsqpH34wAPlwJxql3'
                   recaptcha = <Captcha ReCaptcha>
                    response = 'from Altrui'
                        self = <Hoster UploadedTo>

Frame check_errors in /root/pyload/module/plugins/internal/SimpleHoster.py at line 365
                        self = <Hoster UploadedTo>
                           m = <_sre.SRE_Match object at 0x2b59ac0>
```

### PR DESCRIPTION
**Pull request by GammaC0de**
fix #1854

### CODE REVIEW

**Comment by Bambie42** [comment]
unfortunately this doesn't fix the uploaded.to premium download problem for me.

```
DEBUG   HOSTER UploadedTo[9346]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
DEBUG   HOSTER UploadedTo[9346]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
INFO    HOSTER UploadedTo[9346]: Processing as free download...
DEBUG   HOSTER UploadedTo[9346]: LOAD URL http://uploaded.net/file/foo | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
INFO    HOSTER UploadedTo[9346]: File status: online
INFO    HOSTER UploadedTo[9346]: File size: 524288000 bytes
INFO    HOSTER UploadedTo[9346]: File name: foo.rar
DEBUG   HOSTER UploadedTo[9346]: Previous file info: {}
DEBUG   HOSTER UploadedTo[9346]: File info: {'status': 2, 'url': u'http://uploaded.net/file/foo', 'size': 524288000.0, 'name': 'foo.rar', 'pattern': {'ID': u'foo'}}
INFO    HOSTER UploadedTo[9346]: Updating file info...
DEBUG   HOSTER UploadedTo[9346]: PROCESS URL http://uploaded.net/file/foo | PLUGIN VERSION 0.97
```

**Comment by GammaC0de** [comment]
@Bambie42 sample URL plz

**Comment by manacker** [comment]
I have the same problem. Here is an actual URL: http://uploaded.net/file/y7w3jemb/circushalligalli_hdsl7_s06e02.part01.rar

**Comment by GammaC0de** [comment]
@manacker worked fine for me.
post debug log plz
try refreshing your userplugins

**Comment by manacker** [comment]
@GammaC0de How can I refresh my userplugins. Simply deleting the folder doesn't help, since my base package (on Synology NAS) isn't able to update itself anymore (The requested URL /check/0.4.9/ was not found on this server.)

**Comment by Bambie42** [comment]
still the same problem
```
98	24.09.2015 17:44:35	DEBUG	CAPTCHA UploadedTo[9487]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_Vuse7JGCYIcVFB3ag1wrT0zg9QHSzSW8qYlpm2vwvl_eLl1Uefs2l-02nuBnbFusHhsifgOOKXFmweHzKpK3OrWITgj4Tf8YHMfTKYj-e3R-3278m7FjuuzUcPuK28NdfGQlQiyeoZvZqC-78c4NITl3Beb7XtoflXqJuXo6TZ9Fe3FTSe91RzWwm1pbDzsnOUyOiTsIGorhD2Vkd9IIYWge3bdmww'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
97	24.09.2015 17:44:35	DEBUG	CAPTCHA UploadedTo[9487]: ReCaptcha | Second challenge: 03AHJ_Vuse7JGCYIcVFB3ag1wrT0zg9QHSzSW8qYlpm2vwvl_eLl1Uefs2l-02nuBnbFusHhsifgOOKXFmweHzKpK3OrWITgj4Tf8YHMfTKYj-e3R-3278m7FjuuzUcPuK28NdfGQlQiyeoZvZqC-78c4NITl3Beb7XtoflXqJuXo6TZ9Fe3FTSe91RzWwm1pbDzsnOUyOiTsIGorhD2Vkd9IIYWge3bdmww
96	24.09.2015 17:44:35	DEBUG	HOSTER UploadedTo[9487]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_VuuYoRC2Yb261acMac9RGH8PhTDmbCKXk98gAmcIJeidIWdLzh8DXY7MhJkybfBsMbSehLKjhwbZo18B21JB24Z9U9YJCICfoC1qRC_z-tOOcuIvxEVe_Z7wuVvo5jSWgeoCDo13RvsW723z8FgZ4_D_cJGOUkwWSutq9ImXsVWKqjNndXe2nQi9R9Qz3g4LYlOs1wHt', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
95	24.09.2015 17:44:35	DEBUG	HOSTER UploadedTo[9487]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
94	24.09.2015 17:44:35	DEBUG	CAPTCHA UploadedTo[9487]: ReCaptcha | Challenge: 03AHJ_VuuYoRC2Yb261acMac9RGH8PhTDmbCKXk98gAmcIJeidIWdLzh8DXY7MhJkybfBsMbSehLKjhwbZo18B21JB24Z9U9YJCICfoC1qRC_z-tOOcuIvxEVe_Z7wuVvo5jSWgeoCDo13RvsW723z8FgZ4_D_cJGOUkwWSutq9ImXsVWKqjNndXe2nQi9R9Qz3g4LYlOs1wHt
93	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
92	24.09.2015 17:44:34	DEBUG	CAPTCHA UploadedTo[9487]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
91	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
90	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
89	24.09.2015 17:44:34	INFO	HOSTER UploadedTo[9487]: Processing as free download...
88	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: LOAD URL http://uploaded.net/file/y7w3jemb | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
87	24.09.2015 17:44:34	INFO	HOSTER UploadedTo[9487]: File status: online
86	24.09.2015 17:44:34	INFO	HOSTER UploadedTo[9487]: File size: 106954752 bytes
85	24.09.2015 17:44:34	INFO	HOSTER UploadedTo[9487]: File name: circushalligalli_hdsl7_s06e02.part01.rar
84	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: Previous file info: {}
83	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: File info: {'status': 2, 'url': u'http://uploaded.net/file/y7w3jemb', 'size': 106954752.0, 'name': 'circushalligalli_hdsl7_s06e02.part01.rar', 'pattern': {'ID': u'y7w3jemb'}}
82	24.09.2015 17:44:34	INFO	HOSTER UploadedTo[9487]: Updating file info...
81	24.09.2015 17:44:34	DEBUG	HOSTER UploadedTo[9487]: PROCESS URL http://uploaded.net/file/y7w3jemb/circushalligalli_hdsl7_s06e02.part01.rar | PLUGIN VERSION 0.97
80	24.09.2015 17:44:34	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
79	24.09.2015 17:44:34	DEBUG	ADDON UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
78	24.09.2015 17:44:34	INFO	Download starts: http://uploaded.net/file/y7w3jemb/circushalligalli_hdsl7_s06e02.part01.rar
```

**Comment by GammaC0de** [comment]
@manacker
backup your `userplugins` and `UpdateManager.py`
stop pyLoad
delete `userplugins` folder
replace the original `UpdateManager.py` (not the one inside `userplugins`) with this one: https://raw.githubusercontent.com/pyload/pyload/0eb54572e9c600d1ec88b41de8f901899533b4e6/module/plugins/hooks/UpdateManager.py
delete `UpdateManager.pyc`
start pyLoad
wait for update to finish

**Comment by GammaC0de** [comment]
@Bambie42 
> `78  24.09.2015 17:44:34 INFO    Download starts`

so it did download?

**Comment by Bambie42** [comment]
No, I had to enter a captcha. (just a note, my logs a reversed, newest on the top)
I debuged SimpleHoster. self.premium is empty at line 278, so the link is handled as free download instead of using the premium account

**Comment by manacker** [comment]
@GammaC0de thanks, refreshing my userplugins worked. 

Unfortunately the issue still persists, UploadedTo don't recognize my premium status. Here is the debug log:

````
571	24.09.2015 22:08:09	INFO	ACCOUNT UploadedTo: Login user `xxxxxx`...
572	24.09.2015 22:08:09	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
573	24.09.2015 22:08:09	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': 'xxxxxx', 'pw': '*******'} | ref=True | just_header=False
574	24.09.2015 22:08:09	INFO	ACCOUNT UploadedTo: Parsing account info for user `xxxxxx`...
575	24.09.2015 22:08:09	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
576	24.09.2015 22:08:09	DEBUG	ACCOUNT UploadedTo: Account info for user `xxxxxx`: {'login': {'timestamp': 1443125289.300153, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'trafficleft': 563714457600.0, 'options': {'limitdl': ['0']}, 'maxtraffic': None, 'validuntil': 1461161289.74478, 'login': 'xxxxxx', 'password': '**********', 'type': 'UploadedTo', 'valid': True}}
```

```
604	24.09.2015 22:09:05	DEBUG	Redirected import module.plugins.hoster.UploadedTo -> userplugins.hoster.UploadedTo
605	24.09.2015 22:09:05	DEBUG	Redirected import module.plugins.captcha.ReCaptcha -> userplugins.captcha.ReCaptcha
606	24.09.2015 22:09:05	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
607	24.09.2015 22:09:05	INFO	Download skipped: circushalligalli_hdsl7_s06e02.part01.rar due to File exists
608	24.09.2015 22:09:07	INFO	Download starts: circushalligalli_hdsl7_s06e02.part02.rar
609	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: PROCESS URL http://uploaded.net/file/wism31yu | PLUGIN VERSION 0.97
610	24.09.2015 22:09:07	INFO	HOSTER UploadedTo[96]: Updating file info...
611	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: File info: {'status': 2, 'url': u'http://uploaded.net/file/wism31yu', 'size': 106954752.0, 'name': 'circushalligalli_hdsl7_s06e02.part02.rar', 'pattern': {'ID': u'wism31yu'}}
612	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: Previous file info: {}
613	24.09.2015 22:09:07	INFO	HOSTER UploadedTo[96]: File name: circushalligalli_hdsl7_s06e02.part02.rar
614	24.09.2015 22:09:07	INFO	HOSTER UploadedTo[96]: File size: 106954752 bytes
615	24.09.2015 22:09:07	INFO	HOSTER UploadedTo[96]: File status: online
616	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://uploaded.net/file/wism31yu | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
617	24.09.2015 22:09:07	INFO	HOSTER UploadedTo[96]: Processing as free download...
618	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
619	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
620	24.09.2015 22:09:07	DEBUG	CAPTCHA UploadedTo[96]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
621	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
622	24.09.2015 22:09:07	DEBUG	CAPTCHA UploadedTo[96]: ReCaptcha | Challenge: 03AHJ_Vutyq9SiDs4QgGInd1gg8-vrqtT1ydKPv7z0FQUA1iejQ5kSrutu-Gxjza3xD3aFEURsP40LkfSKfyzRaD2bgE3C1kDaRsZ2UOuCDvzVCsNM0ijQJpumxorVf0gOVY3UyC7EVzMflhU0cPk8KZ6Ygx94lphda6Sb5SZXfSrTf4G8KalHl9XZlxc5-P7d-jl9G72ReAgE
623	24.09.2015 22:09:07	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
624	24.09.2015 22:09:08	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_Vutyq9SiDs4QgGInd1gg8-vrqtT1ydKPv7z0FQUA1iejQ5kSrutu-Gxjza3xD3aFEURsP40LkfSKfyzRaD2bgE3C1kDaRsZ2UOuCDvzVCsNM0ijQJpumxorVf0gOVY3UyC7EVzMflhU0cPk8KZ6Ygx94lphda6Sb5SZXfSrTf4G8KalHl9XZlxc5-P7d-jl9G72ReAgE', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
625	24.09.2015 22:09:08	DEBUG	CAPTCHA UploadedTo[96]: ReCaptcha | Second challenge: 03AHJ_VuslYS25SzbNjE2H1u4h6wkj3WA0L5JqPMSZvAPyl8VlHl0nyJnqTZRKpYaXSw7t_UOgbB92oz27J4r2nlsxfIqgJ-C1iQVaD7c-y9mhYvntMYipVhex81vdyVt_43gbExw-vuWE-pNygcvB6GDFJDjHiR4Yz3ogOCUTOkt16y37JUi-SnUEGZByJAxP_CRs1LduCT9ROx33y9D-1eo3qAyo4UGB5w
626	24.09.2015 22:09:08	DEBUG	CAPTCHA UploadedTo[96]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_VuslYS25SzbNjE2H1u4h6wkj3WA0L5JqPMSZvAPyl8VlHl0nyJnqTZRKpYaXSw7t_UOgbB92oz27J4r2nlsxfIqgJ-C1iQVaD7c-y9mhYvntMYipVhex81vdyVt_43gbExw-vuWE-pNygcvB6GDFJDjHiR4Yz3ogOCUTOkt16y37JUi-SnUEGZByJAxP_CRs1LduCT9ROx33y9D-1eo3qAyo4UGB5w'} | req=None | decode=False | multipart=False | post={} | ref=False | just_header=False
627	24.09.2015 22:09:08	DEBUG	HOOK DeathByCaptcha: LOAD URL http://api.dbcapi.me/api/status | cookies=True | get={} | req= | decode=True | multipart=False | post=False | ref=True | just_header=False
628	24.09.2015 22:09:08	DEBUG	HOOK DeathByCaptcha: {"status": 0, "todays_accuracy": 0.94712, "solved_in": 19, "is_service_overloaded": false}
629	24.09.2015 22:09:08	DEBUG	HOOK DeathByCaptcha: LOAD URL http://api.dbcapi.me/api/user | cookies=True | get={} | req= | decode=True | multipart=False | post={'username': u'xxxxxx', 'password': u'xxxxxxxx'} | ref=True | just_header=False
630	24.09.2015 22:09:08	DEBUG	HOOK DeathByCaptcha: {"is_banned": false, "status": 0, "rate": 0.139, "balance": 649.8789, "user": 258509}
631	24.09.2015 22:09:08	INFO	HOOK DeathByCaptcha: Account balance | US$6.499 (4675 captchas left at 0.14 cents each)
632	24.09.2015 22:09:08	DEBUG	HOOK DeathByCaptcha: LOAD URL http://api.dbcapi.me/api/captcha | cookies=True | get={} | req= | decode=True | multipart=True | post={'username': u'xxxxxx', 'password': u'xxxxxxxx', 'captchafile': (10, 'tmp/captcha_image_UploadedTo_34817.jpg')} | ref=True | just_header=False
633	24.09.2015 22:09:09	DEBUG	HOOK DeathByCaptcha: {"status": 0, "captcha": 1942640, "is_correct": true, "text": "fucceeds grepin"}
634	24.09.2015 22:09:14	DEBUG	HOOK DeathByCaptcha: LOAD URL http://api.dbcapi.me/api/captcha/1942640 | cookies=True | get={} | req= | decode=True | multipart=False | post=False | ref=True | just_header=False
635	24.09.2015 22:09:14	DEBUG	HOOK DeathByCaptcha: {"status": 0, "captcha": 1942640, "is_correct": true, "text": "fucceeds grepin"}
636	24.09.2015 22:09:14	DEBUG	HOOK DeathByCaptcha: Result 1942640 : fucceeds grepin
637	24.09.2015 22:09:14	DEBUG	CAPTCHA UploadedTo[96]: ReCaptcha | Result: fucceeds grepin
638	24.09.2015 22:09:14	DEBUG	HOSTER UploadedTo[96]: LOAD URL http://uploaded.net/io/ticket/captcha/wism31yu | cookies=True | get={} | req=None | decode=True | multipart=False | post={'recaptcha_challenge_field': u'03AHJ_VuslYS25SzbNjE2H1u4h6wkj3WA0L5JqPMSZvAPyl8VlHl0nyJnqTZRKpYaXSw7t_UOgbB92oz27J4r2nlsxfIqgJ-C1iQVaD7c-y9mhYvntMYipVhex81vdyVt_43gbExw-vuWE-pNygcvB6GDFJDjHiR4Yz3ogOCUTOkt16y37JUi-SnUEGZByJAxP_CRs1LduCT9ROx33y9D-1eo3qAyo4UGB5w', 'recaptcha_response_field': u'fucceeds grepin'} | ref=True | just_header=False
639	24.09.2015 22:09:15	INFO	HOSTER UploadedTo[96]: Downloading file...
640	24.09.2015 22:09:15	DEBUG	HOSTER UploadedTo[96]: DOWNLOAD URL http://am4-r1f7-stor02.uploaded.net/dl/26427683-6c1d-442b-8f9a-dc396ed5c050 | cookies=True | get={} | disposition=True | post={} | ref=True
641	24.09.2015 22:09:16	DEBUG	Content-Disposition: circushalligalli_hdsl7_s06e02.part02.rar
```

**Comment by GammaC0de** [comment]
OK, as much as I understand, both @manacker and @Bambie42 you are complaining about `UploadedTo` premium does not work.
This is completely different issue than #1854, please open a new issue, thanks.
@vuolter please merge and close #1854 , thanks

**Comment by rlindner81** [comment]
Agree with @GammaC0de the fixes on SimpleHoster affect more than just UploadedTo... @vuolter please merge and close #1858.

**Pull request closed without merging**
