### PR TITLE
PEP8 cleanup and small code modernizations

### PR DESCRIPTION
**Pull request by vuolter**
Compatibility with Python 2.5 should has been preserved.

### CODE REVIEW

**Comment by GammaC0de** [comment]
What  you would like me to do? test this on  python 2.5?

**Comment by vuolter** [comment]
I used only well-know tools to automate this conversion process, so should be no troubles out of there, but you're the plugin mantainer so I ask your opinion about these changes. Firstly, do you like them? :)

**Comment by GammaC0de** [comment]
Yes, I think we should follow the standards for coding style.

**Comment by vuolter** [comment]
Alright, if there are no objections I proceed with the PR merging. 😃

**Comment by Burnout5151** [comment]
Datafile.com seems to be broken. I didn't pull for a while (~2 weeks) until now. Now Datafile.com doesn't work at all. I can't pinpoint it on this patch yet.
I willdo a test without this patch in the coming days

**Comment by GammaC0de** [comment]
What python version are you running?

**Comment by Burnout5151** [comment]
2.7.12

**Comment by GammaC0de** [comment]
Can you start pyLoad from the console with `python pyLoadCore.py -d`, retry Datafile.com and post the log?

**Comment by Burnout5151** [comment]
Okay, I guess I have egg on my face now:
I booted the server today and both Testuploads work. Sorry, false alarm. 

However _Deathbycaptcha_ seems to be broken:
`Traceback (most recent call last):
  File "/home/XXX/pyload/module/CaptchaManager.py", line 69, in handleCaptcha
    plugin.newCaptchaTask(task)
  File "/home/XXX/pyload/module/plugins/internal/Addon.py", line 200, in newCaptchaTask
    return self.captcha_task(task)
  File "/home/XXX/pyload/module/plugins/hooks/DeathByCaptcha.py", line 172, in captcha_task
    self.get_status()
  File "/home/XXX/pyload/module/plugins/hooks/DeathByCaptcha.py", line 123, in get_status
    res = self.api_response("status", False)
  File "/home/XXX/pyload/module/plugins/hooks/DeathByCaptcha.py", line 81, in api_response
    req=req)
  File "/home/XXX/pyload/module/plugins/internal/Plugin.py", line 200, in load
    req.http.c.setopt(pycurl.MAXREDIRS, redirect)
AttributeError: HTTPRequest instance has no attribute 'http'
`
Happens with every every download, e.g.
http://www.datafile.com/d/TWpVek16RXpOREUF9/test1.txt

**Comment by GammaC0de** [comment]
@Burnout5151 Please open a new issue

@vuolter I found python 2.5 exception compatibility issue but the old syntax is not compatible with python 3.6: 
```
26.02.2017 04:07:12 ERROR     Error importing UpdateManager: invalid syntax (UpdateManager.py, line 339)
Traceback (most recent call last):
  File "/root/dummy/pyload/pyload-stable/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/root/dummy/pyload/pyload-stable/module/plugins/hooks/UpdateManager.py", line 339
     except Exception as e:
                       ^
 SyntaxError: invalid syntax
```

For my opinion, I think we can drop python 2.5 compatibility and require python 2.7 as minimum as both optware and optware-ng have python 2.7 packages..
What do you say?

**Comment by GammaC0de** [comment]
@vuolter !?

**Comment by vuolter** [comment]
@GammaC0de Yep, sorry for the delay. Mantain the compatibility with Python 2.5 is no more possible nowdays, but in the branch 1.0.0 I made several legacy layers to assure Python 2.6 compatibility (big commits coming btw) ;)

**Comment by GammaC0de** [comment]
I must say I hate the 79 characters line limit, look whst it has done to [MultiAccount.py#L192](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/MultiAccount.py#L192) and is messing the config lines...

**Pull request merged**
