### PR TITLE
circlecaptcha.py

### PR DESCRIPTION
**Pull request by gsasch**

### CODE REVIEW

**Comment by stickell** [comment]
We can't merge this as it is. You should implement it as a class inside `internal/CaptchaService`

**Comment by gsasch** [comment]
Ok, i've retestet it and i improve speed and stability

The new file is:
https://github.com/gsasch/pyload/blob/stable/module/plugins/internal/ResolveCircleCaptcha.py

**Comment by vuolter** [comment]
Ookay. I'll have a look on it next month.

**Comment by gsasch** [comment]
https://github.com/gsasch/pyload/blob/stable/module/plugins/captcha/ResolveCircleCaptcha.py

**Comment by gsasch** [comment]
do you have news?

**Comment by vuolter** [comment]
@gsasch Please open a new PR. ;)

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/d22cf4a5b0e51716c353e9f2504eb02ae879501d

**Pull request closed without merging**
