### PR TITLE
fix  issue  #1853

### PR DESCRIPTION
**Pull request by mationic**

### CODE REVIEW

**Comment by Bambie42** [comment]
Thank you for this, uploaded premium is working with this

**Comment by Timmaaee** [comment]
Thanks, Uploaded premium is working now.

**Comment by Nippey** [comment]
Thx, SO Premium works again.

**Comment by Koelli91** [comment]
Thanks, ShareOnline-Premium is working with this/these fix/es!

**Comment by dischinator** [comment]
Thanks ul premium is working again with these commits for me.

**Comment by Gronkdalonka** [comment]
Can confirm with this fix ShareOnline, Uploaded.to and Premiumize.me premium downloads are working again

**Comment by nordic-style** [comment]
@vuolter can you pull this, please?

**Comment by b2un0** [comment]
i also can confirm that this patch works really fine.

**Comment by Floyddotnet** [comment]
i also can confirm that merge of the following commits solve the error.

https://github.com/mationic/pyload/commit/5f9d6f992cb889379dd02fe71fe8c5a4b149fc44
https://github.com/mationic/pyload/commit/3b54dce909e07fbc6668c1e1cf19b9d25b61e195
https://github.com/mationic/pyload/commit/44b65e8f1ea367e00da1638e0362f9443b57e760

**Comment by snickers2k** [comment]
for me its " 'NoneType' object has no attribute 'group' " 
so is the group issue the same as the user issue ?

and also for me, it appeared with filecrypt

**Comment by joberreiter** [comment]
> so is the group issue the same as the user issue?

No.

**Comment by vuolter** [comment]
Please check

**Comment by vuolter** [comment]
ThreadManager cannot be update in stable.
Currently multihosters are down... tomorrow the new class MultiAccount will make them working again.

**Comment by nordic-style** [comment]
@vuolter could you write a short notice about what is required to make them work?

**Comment by vuolter** [comment]
An account plugin with `periodical` routine to automatically reload the hoster list.

**Pull request closed without merging**
