### PR TITLE
[ExtractArchive] Some more changes

### PR DESCRIPTION
**Pull request by immenz**
hope thats ok, I'm not familiar with threaded programming. 
If there is an easier way to get the active thread or the connection for displaying the file in Overview please change it.

### CODE REVIEW

**Comment by stickell** [comment]
Remember to always increase the version number or the update manager will not distribute the new version.

Have you tested this enough? If so it's ok for me

**Comment by immenz** [comment]
Sorry, I didn't know there was a automation behind the version number. There are still some little thinks I find and fix step by step, so I wouldn't force the version too high. 

In the next commit I will increase it, I found another bug concerning archives in archives, which I am investigating right now.

**Comment by stickell** [comment]
> There are still some little thinks I find and fix step by step, so I wouldn't force the version too high

Don't worry about that! We don't care. If you think the patch should be available to the users than increase it and distribute.

> In the next commit I will increase it, I found another bug concerning archives in archives, which I am investigating right now.

:+1:

**Comment by vuolter** [comment]
Last time I checked allDownloadsProcessed has no thread argument, but maybe I'm wrong. :S

**Comment by immenz** [comment]
I think '@threaded' adds it. I was surprised that the blank call for manager.startThread() actually sends the thread to extract :D  I was desperate trying to get '@threated' along with a parameter...

**Comment by mbosner** [comment]
i am experiencing double extracts - is that just me?

In the logs it just says "ExtractArchive" once but watching the filesystem it seems that it is extracting everything twice. After the expected file was written it restarts with 0 Bytes and is growing to full size again.

**Comment by immenz** [comment]
most likely you are extracting files with password, where the password itself is allready in your pw file. If the file content itself isn't encrypted, pyload tries extracting without password, only after that it will detect that a password is needed. So it tries again, and again...til the correct pw was used.

**Comment by wastez** [comment]
These are no double extracts, sometimes it trys a other password. (most no password)

**Comment by immenz** [comment]
No more tyring empty password: https://github.com/immenz/pyload/commit/8e87981f54115c9fecf3c916890015ea90482e12

**Comment by wastez** [comment]
Sorry, saw it to late ;)

**Comment by mbosner** [comment]
Well without you last patch i see the following behavior (packages don't have passwords):

```
08.02.2015 19:59:06 INFO      ExtractArchive: Check package: somepackage.stuff
08.02.2015 19:59:06 INFO      ExtractArchive: somepackage.stuff.part001.rar | Extract to: /Downloads/somepackage.stuff/
08.02.2015 20:01:42 INFO      Download starts: another.package.part040.rar
08.02.2015 20:01:43 INFO      UploadedTo: Direct download link detected
08.02.2015 20:02:07 INFO      Download finished: another.package.part040.rar
08.02.2015 20:02:07 INFO      Package finished: another.package
08.02.2015 20:02:08 INFO      ExtractArchive: Check package: somepackage.stuff
08.02.2015 20:02:08 INFO      ExtractArchive: somepackage.stuff.part001.rar | Extract to: /Downloads/somepackage.stuff/
08.02.2015 20:02:13 INFO      ExtractArchive: somepackage.stuff.part001.rar | Extracting finished
08.02.2015 20:02:32 INFO      ExtractArchive: Check package: another.package
```

**Comment by immenz** [comment]
Did you mean archive doesn't need password? How big are the extracted files, which unrar version you use and on what plattform? Could you provied Debug Log?

**Comment by mbosner** [comment]
Yes, the archives do not require a password.

The extracted files are between 10 and 40 GB - this one was around 32GB but it is the same with a 16 GB one.
unrar version: UNRAR 5.00 beta 8 freeware
Platfrom: ubuntu 14.10 server 64 Bit
Python 2.7.8
I don't have a debug log - but i will create one later.

**Comment by mbosner** [comment]
Is it ok to provide you with the debug log via mail (your gmail address?)

**Comment by immenz** [comment]
yes, please do so.

**Comment by VinceGitHub** [comment]
Hi, 
what about the other rar endings? Currently pyload replace the extension of the filename with this regex.
```
NAME_REPLACEMENTS = [(r'\.part\d+\.rar$', ".part.rar")]
```
That one should match files like "filename.part1.rar". But what is with the other "old" endings like ".r00" or ".001"?

**Comment by immenz** [comment]
Funny you mentioned it, that's what i am recently working on.

**Comment by immenz** [comment]
- Added Version Info of Extractor
- Corrected filelist pattern (different list output with Unrar 4 & 5)
- unrar only extracts rar files
- list of targets now only contains normal archives and first parts of multipart files (reducing loops, cleaner log and usable for other extractors than unrar also)
- Changed Multipart behavior: 

that fixes: 
- multiparts were extracted correct, but all extractors wanted to extract if they can (unnecessary "skip" messages in log)
- r00 kind of multiparts weren't recognized as multipart files and therefore not deleted

**Comment by vuolter** [comment]
@immenz I'll have a look at it tomorrow. Please add you credits to ExtractArchive __authors__.

**Comment by zlep** [comment]
Just a question: Should extraction with the unrar_passwords.txt file working? Because if I don't put the password into the package I'm getting:

ERROR   No password found
ERROR	ExtractArchive: xample.part1.rar | Extract failed

**Comment by immenz** [comment]
Yes, last tests I always made with password protected files, where the password is in the txt file. Please check if the name of your password file corresponds with the name in the settings. I think @vuolter changed it standard to "archive_password.txt", maybe this is the bug that settings are not saved.

**Comment by zlep** [comment]
Thanks. Seems to be working now. I just deleted the file and created a new one.

**Comment by mbosner** [comment]
@vuolter are there issues that prevent merging ?

**Comment by wastez** [comment]
@mbosner 
Could be that it wasn´t merged because the pull request is still open.

But it would be good to merge it as soon as possible because this version is working a lot better then the previous.

**Comment by vuolter** [comment]
Sorry guys, I'm checking and merging right now.

**Comment by wastez** [comment]
@immenz 
I found another bug when deleting files.
Part1 is deleted correctly but the otherwise parts are deleted one folder to deep. 
Herr is the log:
11.02.2015 16:14:46 DEBUG     ExtractArchive: Would delete: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/pll503.part1.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/pll503.part3.rar, /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/pll503.part2.rar
11.02.2015 16:14:46 INFO      ExtractArchive: Deleting 3 files
11.02.2015 16:14:46 DEBUG     ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/pll503.part3.rar does not exists
11.02.2015 16:14:46 DEBUG     ExtractArchive: /media/02aa647a-4695-4417-b44d-bafe779f5393/Downloads/Extracted/pll503.part2.rar does not exists
11.02.2015 16:14:46 INFO      ExtractArchive: pll503.part1.rar | Extracting finished

**Comment by immenz** [comment]
thanks, should be fixed

**Comment by wastez** [comment]
Thanks, it´s working now as it should

**Comment by mbosner** [comment]
@vuolter anything we can help out?
@imment thx for the quick fix.

**Comment by vuolter** [comment]
But don't panic, I'll break it again soon as I can! :P

**Comment by immenz** [comment]
Happy to help you with that :)

**Comment by threaded** [comment]
Hi guys,

I’m getting included on your communications in error.

Thanks,
amanda

**Comment by stickell** [comment]
@threaded: Just click **Unsubscribe**. However it's closed now

**Pull request merged**
