### PR TITLE
change default octal values to strings

### PR DESCRIPTION
**Pull request by pyblub**
### Type of request:

- [x] Bugfix
- [ ] Code cosmetics
- [ ] Feature enhancement
- [ ] New feature
- [ ] New plugin
- [ ] Plugin bugfix/enhancement

### Short description:

change default octal values to strings

replace oct with to_str as values are already strings
int function for base 8 conversion expects a string object

### Additional info:

The values in the default config are integers so using the function oct would work, but when reading in the config file, the values are strings. Function oct expects an integer and throws an error when passing a string.

### CODE REVIEW

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/0879f786cc50647b67b635d54d1d86ca50a51c72

**Comment by GammaC0de** [comment]
Shouln't is be:
```
InputType.Octal: lambda x: int(x, 8)
```
This will get a "644" or "0o644" and return 420 decimal, `oct()` returns a string...

**Comment by pyblub** [comment]
At the moment the octal value that is parsed can be an int (from the default config) or a string when parsed from the config file.

To handle both cases you might need a `if isinstance(x, str/int)`. Because the function `int()` cannot handle strings in the format '0oXXX', and `int(x, base=8)` only works with strings. That's why my suggestion was to change them to strings, because in the code the int with a base is used e.g. `int(self.pyload.config.get('permission', 'filemode'), 8)`

@GammaC0de if you do your way, you need a conversion when writing the config as well. Also you have to change the default config octal values to strings, as I did.

It you don't want to use `to_str`, which I don't like either, you can change it to:
`InputType.Octal: lambda x: oct(int(x, 8))`
and change the default octal values to strings by adding quotes, if you want to have some kind of check to see if `x` is actually an octal value.

**Comment by GammaC0de** [comment]
One note: `isinstance()` does not work for base types like int, you should use `if type(X) == int`.

Actually int() does accept strings like "0o644", at  least python 2.7:
```python
>>> int("0o644", 8)
420
```

**Comment by pyblub** [comment]
@GammaC0de `int("0o644", 8)` works and expects a string, but `int("0o644")` does not.
About isinstance (tested with python 2.7 and 3.6):
```
>>> isinstance('8', int)
False
>>> isinstance(8, int)
True
```

**Comment by GammaC0de** [comment]
Well, I had issues with it in the past:
Issue #2766: https://github.com/pyload/pyload/commit/0d342902653c977115583e6e0f35faa7c527ea57

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/1a0babcbdb2cfefae77f24ff84a471a9509f2da6

**Comment by pyblub** [comment]
> 1a0babc

only the changes in  pyload/config/default.py and pyload/config/parser.py are required.

the other changes break everything again.

**Comment by GammaC0de** [comment]
The solution is so simple:
Every type should have its own *set* **and** *get* methods.

**Comment by pyblub** [comment]
@GammaC0de definitely the cleanest solution. Also a validation if the values are correct, would be helpful.

**Pull request closed without merging**
